apiVersion: v1
kind: Service
metadata:
  name: plex-lan
  namespace: default
  annotations:
    external-dns.alpha.kubernetes.io/hostname: plex-lan.prod.myrobertson.net
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    app.kubernetes.io/instance: plex
    app.kubernetes.io/name: plex-media-server
  ports:
    - name: pms
      protocol: TCP
      port: 32400
      targetPort: 32400
