apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: plex-lxc-migration
  namespace: default
spec:
  type: kv-v2
  mount: secret
  path: plex/prod/migration
  refreshAfter: 60s
  destination:
    create: true
    name: plex-lxc-migration
