apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: task-control-plane
resources:
  - namespace.yaml
  - configmaps.yaml
  - secret-stubs.yaml
  - postgres
  - vikunja
  # - ingress-skeleton.yaml
