apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: task-control-plane-openai
spec:
  type: kv-v2
  mount: secret
  path: task-control-plane/env/openai
  refreshAfter: 60s
  destination:
    create: true
    name: task-control-plane-openai
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: task-control-plane-app
spec:
  type: kv-v2
  mount: secret
  path: task-control-plane/env/app
  refreshAfter: 60s
  destination:
    create: true
    name: task-control-plane-app
---
apiVersion: v1
kind: Secret
metadata:
  name: vikunja-oidc-secret
type: Opaque
stringData:
  client_id: vikunja_prod
  client_secret: $2b$12$G4e2wFGmXCHkQowZZZKOrecbdJik.gd7L5ORyoRVOL7uMZue8SpBW
