apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
spec:
  enable: false
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: kube-prometheus-stack
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  driftDetection:
    mode: enabled
    ignore:
      # Ignore "validated" annotation which is not inserted during install
      - paths: [ "/metadata/annotations/prometheus-operator-validated" ]
        target:
          kind: PrometheusRule
  valuesFrom:
  - kind: ConfigMap
    name: flux-kube-state-metrics-config
    valuesKey: kube-state-metrics-config.yaml
  # https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/values.yaml
  values:
    alertmanager:
      enabled: true
      config:
        global:
          resolve_timeout: 5m
        route:
          receiver: 'gotify-receiver'
          group_by: ['alertname']
          group_wait: 30s
          group_interval: 5m
          repeat_interval: 12h
          routes:
            - match:
                severity: critical
              receiver: gotify-receiver
        receivers:
          - name: 'gotify-receiver'
            webhook_configs:
              - url: 'http://gotify-bridge.monitoring.svc.cluster.local/gotify_webhook'
                send_resolved: true
      alertmanagerSpec:
        storage:
          volumeClaimTemplate:
            spec:
              accessModes: ["ReadWriteMany"]
              resources:
                requests:
                  storage: 10Gi
              storageClassName: synology-iscsi-storage-delete
    kubeScheduler:
      serviceMonitor:
        ## Skip TLS certificate validation when scraping
        insecureSkipVerify: true

    kubeControllerManager:
      serviceMonitor:
        ## Skip TLS certificate validation when scraping
        insecureSkipVerify: true

    kubeEtcd:
      enabled: true
      service:
        selector:
          k8s-app: kube-controller-manager 
        enabled: true
        port: 2381
        targetPort: 2381
      serviceMonitor:
        relabelings:   # Add nodename label
          - sourceLabels: [__meta_kubernetes_pod_node_name]
            separator: ;
            regex: ^(.*)$
            targetLabel: nodename
            replacement: $1
            action: replace
        metricRelabelings:   # Remove pod label
          - action: labeldrop
            regex: pod
    
    prometheus:
      prometheusSpec:
        retention: 24h
        resources:
          requests:
            cpu: 200m
            memory: 200Mi
        podMonitorNamespaceSelector: { }
        podMonitorSelector:
          matchLabels:
            app.kubernetes.io/component: monitoring
        podMonitorSelectorNilUsesHelmValues: false
        serviceMonitorSelectorNilUsesHelmValues: false
      storageSpec:
        volumeClaimTemplate:
          spec:
            accessModes: ["ReadWriteMany"]
            resources:
              requests:
                storage: 50Gi
            storageClassName: synology-iscsi-storage-delete
        
   
