apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grafana
spec:
  values:
    ingress:
      main:
        enabled: true
        hosts:
          - grafana.staging.myrobertson.net
    grafana:
      api:
        general:
          baseUrl: https://grafana.staging.myrobertson.net

   