apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: bazarr
spec:
  values:

    bazarr:
      api:
        general:
          baseUrl: https://bazarr.myrobertson.com
    workload:
      main:
        replicas: 1
    persistence:
      media:
        enabled: true
