apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
  - ../../base/bazarr
  - httpRoute.yaml
  - auth-policy.yaml
patches:
  - path: bazarr-values.yaml
    target:
      kind: HelmRelease
