apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: syncthing-config-ceph-v2
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  storageClassName: csi-cephfs-sc
  volumeMode: Filesystem
