apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
  - ../../base/syncthing
  - gateway.yaml
  - config-ceph-pvc-v2.yaml
patches:
  - path: syncthing-values.yaml
    target:
      kind: HelmRelease
  - patch: |
      - op: replace
        path: /spec/values/persistence/config/existingClaim
        value: syncthing-config-ceph-v2
    target:
      kind: HelmRelease
      name: syncthing
  - patch: |
      - op: replace
        path: /metadata/annotations/cert-manager.io~1common-name
        value: syncthing.staging.myrobertson.net
      - op: replace
        path: /spec/listeners/0/hostname
        value: syncthing.staging.myrobertson.net
      - op: replace
        path: /spec/infrastructure/annotations/external-dns.alpha.kubernetes.io~1hostname
        value: syncthing.staging.myrobertson.net
    target:
      kind: Gateway
      name: syncthing
  - patch: |
      - op: replace
        path: /spec/hostnames/0
        value: syncthing.staging.myrobertson.net
    target:
      kind: HTTPRoute
      name: syncthing
