apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sonarr
spec:
  values:

    sonarr:
      api:
        general:
          baseUrl: https://sonarr.staging.myrobertson.net
    workload:
      main:
        replicas: 0
   