apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: netbox
  namespace: netbox
spec:
  interval: 12h
  chartRef:
    kind: OCIRepository
    name: netbox
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  values:
    global:
      security:
        allowInsecureImages: true
    persistence:
      enabled: false
    storages:
      default:
        BACKEND: "storages.backends.s3.S3Storage"
        OPTIONS:
          endpoint_url: "http://${BUCKET_HOST}:${BUCKET_PORT}"
   
    extraEnvs:
    - name: AWS_ACCESS_KEY_ID
      valueFrom:
        secretKeyRef:
          key: AWS_ACCESS_KEY_ID
          name: netbox-s3
    - name: AWS_SECRET_ACCESS_KEY
      valueFrom:
        secretKeyRef:
          key: AWS_SECRET_ACCESS_KEY
          name: netbox-s3
    - name: AWS_STORAGE_BUCKET_NAME
      valueFrom:
        configMapKeyRef:
          name: netbox-s3
          key: BUCKET_NAME
    - name: AWS_S3_REGION_NAME
      valueFrom:
        configMapKeyRef:
          name: netbox-s3
          key: BUCKET_REGION
    - name: BUCKET_HOST
      valueFrom:
        configMapKeyRef:
          name: netbox-s3
          key: BUCKET_HOST
    - name: BUCKET_PORT
      valueFrom:
        configMapKeyRef:
          name: netbox-s3
          key: BUCKET_PORT
    - name: PG_DATABASE_NAME
      valueFrom:
        secretKeyRef:
          name: netbox-cluster-app
          key: dbname
    - name: PG_USER_NAME
      valueFrom:
        secretKeyRef:
          key: username
          name: netbox-cluster-app
    - name: PG_PASSWORD
      valueFrom:
        secretKeyRef:
          key: password
          name: netbox-cluster-app
    - name: PG_DATABASE_RW_SERVICE_HOST
      valueFrom:
        secretKeyRef:
          key: host
          name: netbox-cluster-app

    valkey:
      primary:
        containerSecurityContext:
          capabilities:
            drop: []
            add: ["ALL"]
      replica:
        containerSecurityContext:
          capabilities:
            drop: []
            add: ["ALL"]
      volumePermissions:
        enabled: true
        image:
          repository: bitnamisecure/os-shell
          tag: latest
      global:
        security:
          allowInsecureImages: true
      image:
        repository: bitnamisecure/valkey
        tag: latest
        debug: true
    postgresql:
      enabled: false
    externalDatabase:
      host: "${PG_DATABASE_RW_SERVICE_HOST}"
      port: 5432
      database: "${PG_DATABASE_NAME}"
      username: "${PG_USER_NAME}"
      password: "${PG_PASSWORD}"
      existingSecretName: "netbox-cluster-app"
      existingSecretKey: password

      # The following settings also apply when using the bundled PostgreSQL chart:
      engine: django.db.backends.postgresql
      connMaxAge: 300
      disableServerSideCursors: false
      ## @param externalDatabase.options Additional PostgreSQL client parameters
      ## Ref: https://www.postgresql.org/docs/current/libpq-connect.html#LIBPQ-PARAMKEYWORDS
      ##
      options:
        sslmode: "prefer"
        target_session_attrs: "read-write"


    # Ensure at least one web pod stays available at all times
    pdb:
      enabled: true
      minAvailable: 1

    # Allow one worker to be evicted at a time
    worker:
      pdb:
        enabled: true
        maxUnavailable: 1
      extraEnvs:
      - name: AWS_ACCESS_KEY_ID
        valueFrom:
          secretKeyRef:
            key: AWS_ACCESS_KEY_ID
            name: netbox-s3
      - name: AWS_SECRET_ACCESS_KEY
        valueFrom:
          secretKeyRef:
            key: AWS_SECRET_ACCESS_KEY
            name: netbox-s3
      - name: AWS_STORAGE_BUCKET_NAME
        valueFrom:
          configMapKeyRef:
            name: netbox-s3
            key: BUCKET_NAME
      - name: AWS_S3_REGION_NAME
        valueFrom:
          configMapKeyRef:
            name: netbox-s3
            key: BUCKET_REGION
      - name: BUCKET_HOST
        valueFrom:
          configMapKeyRef:
            name: netbox-s3
            key: BUCKET_HOST
      - name: BUCKET_PORT
        valueFrom:
          configMapKeyRef:
            name: netbox-s3
            key: BUCKET_PORT
      - name: PG_DATABASE_NAME
        valueFrom:
          secretKeyRef:
            name: netbox-cluster-app
            key: dbname
      - name: PG_USER_NAME
        valueFrom:
          secretKeyRef:
            key: username
            name: netbox-cluster-app
      - name: PG_PASSWORD
        valueFrom:
          secretKeyRef:
            key: password
            name: netbox-cluster-app
      - name: PG_DATABASE_RW_SERVICE_HOST
        valueFrom:
          secretKeyRef:
            key: host
            name: netbox-cluster-app
      - name: DB_WAIT_DEBUG
        value: 1


    
