---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: cloudflare-api-token-secret
  namespace: default
spec:
  type: kv-v2
  mount: secret
  path: cloudflare
  refreshAfter: 60s
  destination:
    create: true
    name: cloudflare-api-token-secret
