apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
  - ../../base/prowlarr
  - httpRoute.yaml
  - auth-policy.yaml
patches:
  - path: prowlarr-values.yaml
    target:
      kind: HelmRelease
  - patch: |
      $patch: delete
      apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: prowlarr-config-ceph
    target:
      kind: PersistentVolumeClaim
      name: prowlarr-config-ceph
  - patch: |
      - op: replace
        path: /spec/resources/requests/storage
        value: 2Gi
    target:
      kind: PersistentVolumeClaim
      name: prowlarr-data-files-pvc