apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prowlarr
spec:
  postRenderers:
    - kustomize:
        patches:
          - target:
              kind: Deployment
              name: prowlarr
            patch: |
              apiVersion: apps/v1
              kind: Deployment
              metadata:
                name: prowlarr
              spec:
                template:
                  spec:
                    containers:
                      - name: prowlarr
                        resources:
                          requests:
                            memory: 512Mi
                      - name: prowlarr-exportarr
                        resources:
                          requests:
                            memory: 128Mi
  values:

    prowlarr:
      api:
        general:
          baseUrl: https://prowlarr.myrobertson.com
    workload:
      main:
        replicas: 1
