apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
  - data-ceph-pvc.yaml
  - deployment.yaml
  - migration-secret.yaml
  - service.yaml
  - synology-data-seed-job.yaml
