apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: tautulli-synology-migration
  namespace: default
spec:
  type: kv-v2
  mount: secret
  path: tautulli/prod/migration
  refreshAfter: 60s
  destination:
    create: true
    name: tautulli-synology-migration
