apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: keycloak-cnpg
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: keycloak
spec:
  instances: 3
  enablePDB: true
  enableSuperuserAccess: false
  primaryUpdateStrategy: unsupervised
  primaryUpdateMethod: switchover
  affinity:
    enablePodAntiAffinity: true
    podAntiAffinityType: required
    topologyKey: kubernetes.io/hostname
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: node-role.kubernetes.io/control-plane
                operator: DoesNotExist
  storage:
    size: 10Gi
    storageClass: ceph-block
  walStorage:
    size: 2Gi
    storageClass: ceph-block
  managed:
    roles:
      - name: keycloak
        login: true
        superuser: false
  bootstrap:
    initdb:
      database: keycloak
      owner: keycloak
