apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: keycloak-secret
  namespace: default
spec:
  type: kv-v2
  mount: secret
  path: keycloak/stage
  refreshAfter: 60s
  destination:
    create: true
    name: keycloak-secret
    overwrite: true
