apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
  - ../../base/volsync
  - restic-repository-secrets.yaml
  - replicationsources.yaml
patches:
  - path: volsync-values.yaml
    target:
      kind: HelmRelease
