---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: authelia-config-ceph-backup
spec:
  sourcePVC: authelia-config-ceph
  activeDeadlineSeconds: 14400
  trigger:
    schedule: "0 * * * *"
  restic:
    repository: restic-config-authelia
    pruneIntervalDays: 1
    retain:
      hourly: 4
      daily: 0
      weekly: 0
      monthly: 0
      yearly: 0
    copyMethod: Clone
    cacheStorageClassName: ceph-filesystem
    moverResources:
      requests:
        cpu: "500m"
        memory: "1Gi"
      limits:
        cpu: "2"
        memory: "4Gi"
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: bitwarden-data-ceph-backup
spec:
  sourcePVC: bitwarden-data-ceph
  activeDeadlineSeconds: 14400
  trigger:
    schedule: "55 * * * *"
  restic:
    repository: restic-config-bitwarden
    pruneIntervalDays: 1
    retain:
      hourly: 4
      daily: 0
      weekly: 0
      monthly: 0
      yearly: 0
    copyMethod: Clone
    cacheStorageClassName: ceph-filesystem
    moverResources:
      requests:
        cpu: "500m"
        memory: "1Gi"
      limits:
        cpu: "2"
        memory: "4Gi"
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: gotify-data-ceph-backup
spec:
  sourcePVC: gotify-data-ceph
  activeDeadlineSeconds: 14400
  trigger:
    schedule: "35 * * * *"
  restic:
    repository: restic-config-gotify
    pruneIntervalDays: 1
    retain:
      hourly: 4
      daily: 0
      weekly: 0
      monthly: 0
      yearly: 0
    copyMethod: Clone
    cacheStorageClassName: ceph-filesystem
    moverResources:
      requests:
        cpu: "500m"
        memory: "1Gi"
      limits:
        cpu: "2"
        memory: "4Gi"
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: netbootxyz-config-ceph-backup
spec:
  sourcePVC: netbootxyz-config-ceph
  activeDeadlineSeconds: 14400
  trigger:
    schedule: "27 * * * *"
  restic:
    repository: restic-config-netbootxyz-config
    pruneIntervalDays: 1
    retain:
      hourly: 4
      daily: 0
      weekly: 0
      monthly: 0
      yearly: 0
    copyMethod: Clone
    cacheStorageClassName: ceph-filesystem
    moverResources:
      requests:
        cpu: "500m"
        memory: "1Gi"
      limits:
        cpu: "2"
        memory: "4Gi"
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: netbootxyz-assets-ceph-backup
spec:
  sourcePVC: netbootxyz-assets-ceph
  activeDeadlineSeconds: 14400
  trigger:
    schedule: "28 * * * *"
  restic:
    repository: restic-config-netbootxyz-assets
    pruneIntervalDays: 1
    retain:
      hourly: 4
      daily: 0
      weekly: 0
      monthly: 0
      yearly: 0
    copyMethod: Clone
    cacheStorageClassName: ceph-filesystem
    moverResources:
      requests:
        cpu: "500m"
        memory: "1Gi"
      limits:
        cpu: "2"
        memory: "4Gi"
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: cluster-authelia-ceph-1-backup
spec:
  sourcePVC: cluster-authelia-ceph-1
  activeDeadlineSeconds: 14400
  trigger:
    schedule: "32 * * * *"
  restic:
    repository: restic-config-authelia-cnpg-data
    pruneIntervalDays: 1
    retain:
      hourly: 4
      daily: 0
      weekly: 0
      monthly: 0
      yearly: 0
    copyMethod: Clone
    cacheStorageClassName: ceph-filesystem
    moverSecurityContext:
      runAsUser: 26
      runAsGroup: 26
      fsGroup: 26
    moverResources:
      requests:
        cpu: "500m"
        memory: "1Gi"
      limits:
        cpu: "2"
        memory: "4Gi"
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: immich-data-files-pvc-ceph-backup
spec:
  sourcePVC: immich-data-files-pvc-ceph
  activeDeadlineSeconds: 14400
  trigger:
    schedule: "10 * * * *"
  restic:
    repository: restic-config-immich
    pruneIntervalDays: 1
    retain:
      hourly: 4
      daily: 0
      weekly: 0
      monthly: 0
      yearly: 0
    copyMethod: Direct
    cacheStorageClassName: ceph-filesystem
    moverResources:
      requests:
        cpu: "500m"
        memory: "2Gi"
      limits:
        cpu: "4"
        memory: "8Gi"
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: cluster-immich-ceph-1-backup
spec:
  sourcePVC: cluster-immich-ceph-1
  activeDeadlineSeconds: 14400
  trigger:
    schedule: "12 * * * *"
  restic:
    repository: restic-config-immich-cnpg-data
    pruneIntervalDays: 1
    retain:
      hourly: 4
      daily: 0
      weekly: 0
      monthly: 0
      yearly: 0
    copyMethod: Clone
    cacheStorageClassName: ceph-filesystem
    moverSecurityContext:
      runAsUser: 26
      runAsGroup: 26
      fsGroup: 26
    moverResources:
      requests:
        cpu: "500m"
        memory: "1Gi"
      limits:
        cpu: "2"
        memory: "4Gi"
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: lidarr-config-ceph-backup
spec:
  sourcePVC: lidarr-config-ceph
  activeDeadlineSeconds: 14400
  trigger:
    schedule: "20 * * * *"
  restic:
    repository: restic-config-lidarr
    pruneIntervalDays: 1
    retain:
      hourly: 4
      daily: 0
      weekly: 0
      monthly: 0
      yearly: 0
    copyMethod: Clone
    cacheStorageClassName: ceph-filesystem
    moverSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
    moverResources:
      requests:
        cpu: "500m"
        memory: "1Gi"
      limits:
        cpu: "2"
        memory: "4Gi"
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: mealie-data-ceph-backup
spec:
  sourcePVC: mealie-data-ceph
  activeDeadlineSeconds: 14400
  trigger:
    schedule: "30 * * * *"
  restic:
    repository: restic-config-mealie
    pruneIntervalDays: 1
    retain:
      hourly: 4
      daily: 0
      weekly: 0
      monthly: 0
      yearly: 0
    copyMethod: Clone
    cacheStorageClassName: ceph-filesystem
    moverResources:
      requests:
        cpu: "500m"
        memory: "1Gi"
      limits:
        cpu: "2"
        memory: "4Gi"
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: mealie-cnpg-main-1-backup
spec:
  sourcePVC: mealie-cnpg-main-1
  activeDeadlineSeconds: 14400
  trigger:
    schedule: "34 * * * *"
  restic:
    repository: restic-config-mealie-cnpg-data
    pruneIntervalDays: 1
    retain:
      hourly: 4
      daily: 0
      weekly: 0
      monthly: 0
      yearly: 0
    copyMethod: Clone
    cacheStorageClassName: ceph-filesystem
    moverSecurityContext:
      runAsUser: 26
      runAsGroup: 26
      fsGroup: 26
    moverResources:
      requests:
        cpu: "500m"
        memory: "1Gi"
      limits:
        cpu: "2"
        memory: "4Gi"
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: mealie-cnpg-main-1-wal-backup
spec:
  sourcePVC: mealie-cnpg-main-1-wal
  activeDeadlineSeconds: 14400
  trigger:
    schedule: "44 * * * *"
  restic:
    repository: restic-config-mealie-cnpg-wal
    pruneIntervalDays: 1
    retain:
      hourly: 4
      daily: 0
      weekly: 0
      monthly: 0
      yearly: 0
    copyMethod: Clone
    cacheStorageClassName: ceph-filesystem
    moverSecurityContext:
      runAsUser: 26
      runAsGroup: 26
      fsGroup: 26
    moverResources:
      requests:
        cpu: "500m"
        memory: "1Gi"
      limits:
        cpu: "2"
        memory: "4Gi"
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: overseerr-config-ceph-backup
spec:
  sourcePVC: overseerr-config-ceph
  activeDeadlineSeconds: 14400
  trigger:
    schedule: "40 * * * *"
  restic:
    repository: restic-config-overseerr
    pruneIntervalDays: 1
    retain:
      hourly: 4
      daily: 0
      weekly: 0
      monthly: 0
      yearly: 0
    copyMethod: Clone
    cacheStorageClassName: ceph-filesystem
    moverResources:
      requests:
        cpu: "500m"
        memory: "1Gi"
      limits:
        cpu: "2"
        memory: "4Gi"
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: prowlarr-config-ceph-backup
spec:
  sourcePVC: prowlarr-config-ceph
  activeDeadlineSeconds: 14400
  trigger:
    schedule: "50 * * * *"
  restic:
    repository: restic-config-prowlarr
    pruneIntervalDays: 1
    retain:
      hourly: 4
      daily: 0
      weekly: 0
      monthly: 0
      yearly: 0
    copyMethod: Clone
    cacheStorageClassName: ceph-filesystem
    moverSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
    moverResources:
      requests:
        cpu: "500m"
        memory: "1Gi"
      limits:
        cpu: "2"
        memory: "4Gi"
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: radarr-config-ceph-backup
spec:
  sourcePVC: radarr-config-ceph
  activeDeadlineSeconds: 14400
  trigger:
    schedule: "5 * * * *"
  restic:
    repository: restic-config-radarr
    pruneIntervalDays: 1
    retain:
      hourly: 4
      daily: 0
      weekly: 0
      monthly: 0
      yearly: 0
    copyMethod: Clone
    cacheStorageClassName: ceph-filesystem
    moverSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
    moverResources:
      requests:
        cpu: "500m"
        memory: "1Gi"
      limits:
        cpu: "2"
        memory: "4Gi"
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: sonarr-config-ceph-backup
spec:
  sourcePVC: sonarr-config-ceph
  activeDeadlineSeconds: 14400
  trigger:
    schedule: "15 * * * *"
  restic:
    repository: restic-config-sonarr
    pruneIntervalDays: 1
    retain:
      hourly: 4
      daily: 0
      weekly: 0
      monthly: 0
      yearly: 0
    copyMethod: Clone
    cacheStorageClassName: ceph-filesystem
    moverSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
    moverResources:
      requests:
        cpu: "500m"
        memory: "1Gi"
      limits:
        cpu: "2"
        memory: "4Gi"
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: tautulli-config-ceph-backup
spec:
  sourcePVC: tautulli-config-ceph
  activeDeadlineSeconds: 14400
  trigger:
    schedule: "45 * * * *"
  restic:
    repository: restic-config-tautulli
    pruneIntervalDays: 1
    retain:
      hourly: 4
      daily: 0
      weekly: 0
      monthly: 0
      yearly: 0
    copyMethod: Clone
    cacheStorageClassName: ceph-filesystem
    moverResources:
      requests:
        cpu: "500m"
        memory: "1Gi"
      limits:
        cpu: "2"
        memory: "4Gi"
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: syncthing-config-ceph-backup
spec:
  sourcePVC: syncthing-config-ceph
  activeDeadlineSeconds: 14400
  trigger:
    schedule: "25 * * * *"
  restic:
    repository: restic-config-syncthing
    pruneIntervalDays: 1
    retain:
      hourly: 4
      daily: 0
      weekly: 0
      monthly: 0
      yearly: 0
    copyMethod: Clone
    cacheStorageClassName: ceph-filesystem
    moverSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
    moverResources:
      requests:
        cpu: "500m"
        memory: "1Gi"
      limits:
        cpu: "2"
        memory: "4Gi"
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: trilium-data-ceph-backup
spec:
  sourcePVC: trilium-data-ceph
  activeDeadlineSeconds: 14400
  trigger:
    schedule: "42 * * * *"
  restic:
    repository: restic-config-trilium
    pruneIntervalDays: 1
    retain:
      hourly: 4
      daily: 0
      weekly: 0
      monthly: 0
      yearly: 0
    copyMethod: Clone
    cacheStorageClassName: ceph-filesystem
    moverSecurityContext:
      runAsUser: 1000
      runAsGroup: 1000
      fsGroup: 1000
    moverResources:
      requests:
        cpu: "500m"
        memory: "1Gi"
      limits:
        cpu: "2"
        memory: "4Gi"
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: plex-config-ceph-backup
spec:
  sourcePVC: plex-config-ceph
  activeDeadlineSeconds: 14400
  trigger:
    schedule: "52 * * * *"
  restic:
    repository: restic-config-plex
    pruneIntervalDays: 1
    retain:
      hourly: 4
      daily: 0
      weekly: 0
      monthly: 0
      yearly: 0
    copyMethod: Clone
    cacheStorageClassName: ceph-filesystem
    moverSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
    moverResources:
      requests:
        cpu: "1"
        memory: "4Gi"
      limits:
        cpu: "4"
        memory: "16Gi"
