apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: volsync
spec:
  values:
    workload:
      main:
        replicas: 0
    volsync:
      api:
        general:
          baseUrl: https://volsync.myrobertson.net
