---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: client-info-secret
  namespace: synology-csi
spec:
  encryptedData:
    client-info-template.yml: AgBmx7W2+d6L1sUQaW1E1yi8j0VCZOVbRj4GUQi/QgZ3pvf2KL+Fj9nPfV/JXW9dxrzs7JDPivcejZRZSLGW5qeRkUlP4a537EcPCNr47UMslY61C3zk2SyvODfLZFLHgZJVZKwWel5Plvb0LJClLCRwN0Dk6ZnSOjERSbXtTv7Xznrvs40qw8QRwjIIc/MhT/QUUf3W7Uci4X7XqWAGsF0tyK/2gjqJx7QQy86cDc1dS4ZbdzT/8O6nMKIejonkQ1opqjd+QPDyl4MsfP6Um1KxuJTYmo1zHJxYL4Jjic8k7uhSYDNRqm6FZPoRB7SuMGI7Iq+EimgIGSEbgjokCBzjb8bkY9vvdcvS9RP9RM/wxJ0lkZlelOd9FaYoMwrNO5ec8bryfFEbPxbwedRXzEb4wss3H+65fNH3IJKjIknZFvSTK3XGIDWtVjgGNSX4NOjGv3T9qeYGjpNWJWoPTU5h/BUpSWaOHeQqg0LX2xkTPCXHC7ygXuwoTrvl0OTOjtrowCRgGVg0t6IItNkfZquJii/oA89nyH3+LDibh1/skTFTsteQ/ZzkJFnIrchO4moCEnsdAinbBQAdz+CSLwrbGxlxp69eYLWgZadYYgDyxPL16uEnU7ReqpgrgQcj67pfeqYyUs4qF/dPDJuUrE7jrYAb8pGofFZYJcNEh4KGR/SBnAtryqjIDqxWi90p5MG4frvtmnFyqM5gah2ahtnnUqrLFAxqcld0rSjqLn0Jo3qxi9DlhVn++gYXi2YMghtHkVq2p7H5CSCnIEM7cUvU2A7AvQF21rj5nytI5pEuZlSub2GYI3OExNco4eAwUSEFUPB526u4kUSX8dDLdqdTQBRrekFw+l/OhknITy7xY8HQxyRCghKIRKGrMdVL4XzI8vfEquvOWrlQ6Pmot7ltobBN8hSpxjgQcxb2PylCYZElEp6fxys3FPAffhHEbWfpaLc4bnoGSFKtNtwMOVM3Cg5yB1kkCWXqCl49xEE1QIg/otP49zJ6NBMEiWdFuIZKvniudmVIbv2XZoflKsNbNT+0cM/FM95r549m7vDCQNA35dV4G5Z/5ggUi35Eor0WPIeG1Aj45r2UDcdc4ocbU91K1+Td3sgMMum6sMRP9Lhgu8wrQjMdnf4VjfHkT9wOAFFTQfUyl1JP0XU3QPIbKigjP7nLDDzrzAYvY+P76d27YFQxHenMCBy25Y2/hbUjCRFfp+3IdjpipmCSYhyt8Yq2+d1uvi3z0i6/NSRNy7enJbYzZd8t9cAZoHBCOBGaGQ==
  template:
    metadata:
      name: client-info-secret
      namespace: synology-csi
