apiVersion: redis.redis.opstreelabs.in/v1beta2
kind: Redis
metadata:
  name: task-control-plane-redis
  labels:
    app.kubernetes.io/name: redis
    app.kubernetes.io/component: cache
    app.kubernetes.io/part-of: task-control-plane
spec:
  kubernetesConfig:
    image: redis:7.2.5
    service:
      serviceType: ClusterIP
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 1
        memory: 512Mi
  storage:
    volumeClaimTemplate:
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: ceph-block
        resources:
          requests:
            storage: 2Gi
