apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: cnpg-backup-s3
  namespace: default
spec:
  type: kv-v2
  mount: secret
  path: cnpg/prod/backup-s3
  refreshAfter: 60s
  destination:
    create: true
    name: cnpg-backup-s3
