apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - bitwarden
  - cnpg-backup-secret.yaml
  - authelia
  - external-dns
  - immich
  - lidarr
  - loki-stack
  - mealie
  - overseerr
  - prowlarr
  - radarr
  - shared_storage
  - sonarr
  - syncthing
