apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - bitwarden
  - readarr
  - cnpg-backup-secret.yaml
  - authelia
  - external-dns
  - gotify
  - immich
  - lidarr
  - loki-stack
  - mealie
  - netbootxyz
  - overseerr
  - prowlarr
  - radarr
  - sonarr
  - syncthing
  - tautulli
