apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - bitwarden
  - code-server
  - cnpg-backup-secret.yaml
  - authelia
  - external-dns
  - gotify
  - immich
  - lidarr
  - loki-stack
  - mealie
  - n8n
  - netbootxyz
  - ntfy
  - overseerr
  - plex
  - trilium
  - prowlarr
  - radarr
  - redis-operator
  - sonarr
  - syncthing
  - task-control-plane
  - tautulli
  - volsync
