apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
  - ../../base/netbootxyz
  - httpRoute.yaml
patches:
  - patch: |
      - op: add
        path: /spec/loadBalancerIP
        value: 10.31.0.74
    target:
      kind: Service
      name: netbootxyz-lan
  - patch: |
      - op: replace
        path: /spec/template/spec/volumes/0/persistentVolumeClaim/claimName
        value: netbootxyz-config-ceph-v3
      - op: replace
        path: /spec/template/spec/volumes/1/persistentVolumeClaim/claimName
        value: netbootxyz-assets-ceph-v3
    target:
      kind: Deployment
      name: netbootxyz
  - patch: |
      $patch: delete
      apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: netbootxyz-config-ceph
        namespace: default
    target:
      kind: PersistentVolumeClaim
      name: netbootxyz-config-ceph
  - patch: |
      $patch: delete
      apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: netbootxyz-assets-ceph
        namespace: default
    target:
      kind: PersistentVolumeClaim
      name: netbootxyz-assets-ceph
