apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: immich
spec:
  values:
    controllers:
      main:
        replicas: 1
        containers:
          main:
            image:
              tag: v2.2.3
    server:
      controllers:
        main:
          replicas: 1
          containers:
            main:
              env:
                DB_USERNAME:
                  valueFrom:
                    secretKeyRef:
                      name: cluster-immich-ceph-app
                      key: username
                DB_PASSWORD:
                  valueFrom:
                    secretKeyRef:
                      name: cluster-immich-ceph-app
                      key: password
                DB_DATABASE_NAME:
                  valueFrom:
                    secretKeyRef:
                      name: cluster-immich-ceph-app
                      key: dbname
                DB_HOSTNAME: cluster-immich-ceph-rw