apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: immich
spec:
  values:
    valkey:
      controllers:
        main:
          replicas: 1
      persistence:
        data:
          storageClass: ceph-block
    server:
      controllers:
        main:
          replicas: 3
          affinity:
            podAntiAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                - labelSelector:
                    matchLabels:
                      app.kubernetes.io/name: server
                      app.kubernetes.io/instance: immich
                  topologyKey: kubernetes.io/hostname
          containers:
            main:
              env:
                IMMICH_TELEMETRY_INCLUDE: all
                DB_USERNAME:
                  valueFrom:
                    secretKeyRef:
                      name: cluster-immich-ceph-app
                      key: username
                DB_PASSWORD:
                  valueFrom:
                    secretKeyRef:
                      name: cluster-immich-ceph-app
                      key: password
                DB_DATABASE_NAME:
                  valueFrom:
                    secretKeyRef:
                      name: cluster-immich-ceph-app
                      key: dbname
                DB_HOSTNAME: cluster-immich-ceph-rw
    machine-learning:
      controllers:
        main:
          replicas: 3