apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
  - gateway.yaml
  - ../../base/immich
patches:
  - path: immich-values.yaml
    target:
      kind: HelmRelease
  - patch: |
      - op: replace
        path: /spec/resources/requests/storage
        value: 2Gi
    target:
      kind: PersistentVolumeClaim
      name: immich-data-files-pvc
  - patch: |
      - op: add
        path: /spec/postgresql/shared_preload_libraries/-
        value: "vchord.so"
      - op: replace
        path: /spec/postgresql/imageName
        value: ghcr.io/immich-app/postgres:14-vectorchord0.4.3-pgvectors0.2.0
    target:
      kind: Cluster
      name: cluster-immich