apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: auth-policy-waypoint
  namespace: default
spec:
  targetRefs:
  - kind: Service
    group: ""
    name: radarr
  action: 'CUSTOM'
  provider:
    name:  'authelia'
  rules:
    - to:
        - operation:
            paths: ["/"]
