apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-dns
  namespace: external-dns
spec:
  values:
    logLevel: debug
    provider: 
      name: cloudflare
    env:
      - name: CF_API_KEY
        valueFrom:
          secretKeyRef:
            name: cloudflare-api-key
            key: apiKey
      - name: CF_API_EMAIL
        valueFrom:
          secretKeyRef:
            name: cloudflare-api-key
            key: email
    
    
    
    
    
    