apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-dns-pdns
  namespace: external-dns
spec:
  interval: 30m
  chart:
    spec:
      chart: './charts/external-dns'
      sourceRef:
        kind: GitRepository
        name: external-dns
        namespace: external-dns
      interval: 10m
  values:
    logLevel: debug
    sources:
      - gateway-httproute
      - service
    provider:
      name: pdns
    rbac:
      create: true
      additionalPermissions:
        - apiGroups: [""]
          resources: ["services", "pods", "nodes", "endpoints", "namespaces"]
          verbs: ["get", "watch", "list"]
        - apiGroups: ["networking.k8s.io"]
          resources: ["ingresses", "ingressclasses", "httproutes"]
          verbs: ["get", "watch", "list"]
        - apiGroups: ["gateway.networking.k8s.io"]
          resources: ["gateways", "httproutes"]
          verbs: ["get", "watch", "list"]
        - apiGroups: ["discovery.k8s.io"]
          resources: ["endpointslices"]
          verbs: ["get", "watch", "list"]
    extraArgs:
      - --pdns-server=http://192.168.7.201:8001
      - --pdns-server-id=localhost
      - --pdns-api-key=$(PDNS_API_KEY)
    txtOwnerId: prod.myrobertson.net
    domainFilters:
      - prod.myrobertson.net
    env:
      - name: PDNS_API_KEY
        valueFrom:
          secretKeyRef:
            name: external-dns-pdns-apikey
            key: pdns-api-key
