apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: external-dns
resources:
  - cloudflare-api-key.yaml
  - powerdns-api-key.yaml
  - external-dns-pdns.yaml
  - synology-drive-dnsendpoint.yaml
  - ../../base/external-dns
patches:
  - path: external-dns-values.yaml
    target:
      kind: HelmRelease
      name: external-dns
