---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: external-dns-pdns-apikey
  namespace: external-dns
spec:
  type: kv-v2
  mount: secret
  path: substrate/subdns
  refreshAfter: 60s
  destination:
    create: true
    name: external-dns-pdns-apikey
