apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-data
  namespace: nextcloud
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: synology-nfs-retain
  resources:
    requests:
      storage: 10Ti
  volumeName: nextcloud-data-synology-nfs
