apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prowlarr
spec:
  values:

    prowlarr:
      api:
        general:
          baseUrl: https://prowlarr.staging.myrobertson.net
    server:
      controllers:
        main:
          replicas: 1
   