apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bitwarden-data-ceph
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: csi-cephfs-sc
  resources:
    requests:
      storage: 10Gi
