apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: bitwarden-synology-migration
  namespace: default
spec:
  type: kv-v2
  mount: secret
  path: bitwarden/prod/migration
  refreshAfter: 60s
  destination:
    create: true
    name: bitwarden-synology-migration
