apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ceph-csi-cephfs
  namespace: ceph-csi
spec:
  interval: 30m
  chart:
    spec:
      chart: ceph-csi-cephfs
      sourceRef:
        kind: HelmRepository
        name: ceph-csi
        namespace: ceph-csi
      interval: 24h
  values:
    selinuxMount: false

    provisioner:
      replicaCount: 3

    csiConfig:
      - clusterID: "1b5c261a-cdac-495a-b046-ea5ff229f33a"
        monitors:
          - "192.168.10.3:6789"
        cephFS:
          radosNamespace: "cephfs-csi-standalone"

    encryptionKMSConfig:
        encryptionKMSType: vault
        vaultAddress: https://vault.myrobertson.net:8200
        vaultAuthPath: /v1/auth/kubernetes/login
        vaultRole: csi-kubernetes
        vaultPassphraseRoot: /v1/secret
        vaultPassphrasePath: ceph-csi/
        vaultCAVerify: "false"

    storageClass:
      create: true
      clusterID: 1b5c261a-cdac-495a-b046-ea5ff229f33a
      encrypted: false
      encryptionKMSID: kubernetes
      fsName: kubernetes-prod-cephfs
      pool: kubernetes-prod-cephfs_data
      reclaimPolicy: Retain
      allowVolumeExpansion: true
      provisionerSecretNamespace: ceph-csi
      controllerExpandSecretNamespace: ceph-csi
      controllerPublishSecretNamespace: ceph-csi
      nodeStageSecretNamespace: ceph-csi

    volumeSnapshotClass:
      create: false
      deletionPolicy: Delete
      clusterID: 1b5c261a-cdac-495a-b046-ea5ff229f33a

  postRenderers:
    - kustomize:
        patches:
          - target:
              kind: ConfigMap
              name: ceph-config
            patch: |
              - op: replace
                path: /data/ceph.conf
                value: "[global]\n  auth_cluster_required = cephx\n  auth_service_required = cephx\n  auth_client_required = cephx\n  fuse_big_writes = true\n  mon_op_timeout = 30\n  osd_op_timeout = 30\n"