---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: csi-cephfs-secret
  namespace: ceph-csi
spec:
  type: kv-v2
  mount: secret
  path: proxmox/cl0/ceph/csi-cephfs-secret
  refreshAfter: 60s
  destination:
    create: true
    name: csi-cephfs-secret
