apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: guacamole
resources:
  - namespace.yaml
  - postgres.yaml
  - postgres-init-job.yaml
  - guacd-deployment.yaml
  - guacd-service.yaml
  - guacamole-deployment.yaml
  - guacamole-service.yaml
  - networkpolicy.yaml

