apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
  - repository.yaml
  - release.yaml
  - gateway.yaml
  - mealie-cnpg-main-1-permissions-fix.yaml
  - mealie-cnpg-main-1-wal-permissions-fix.yaml

