---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: mealie-oidc-secret
spec:
  type: kv-v2
  mount: secret
  path:  oidc/dev
  refreshAfter: 60s
  destination:
    create: true
    name: mealie-oidc