---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mealie
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: mealie
  install:
    disableWait: true
  upgrade:
    disableWait: true
  values:
    mealie:
      api:
        general:
          baseUrl: https://mealie.dev.myrobertson.net
    persistence:
      data:
        enabled: true
        existingClaim: mealie-data-ceph
        targetSelector:
          main:
            main:
              mountPath: /app/data
    cnpg:
      main:
        cluster:
          imageName: ghcr.io/cloudnative-pg/postgresql:18.1-system-trixie
          instances: 1
          storage:
            size: 2Gi
            storageClass: ceph-block
          walStorage:
            size: 2Gi
            storageClass: ceph-block
        