---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mealie
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: mealie
  values:
    mealie:
      api:
        general:
          baseUrl: https://mealie.dev.myrobertson.net
        
        oidc:
          auth_enabled: true
          signup_enabled: true
          configuration_url: "https://auth.myrobertson.com/.well-known/openid-configuration"
          client_id: "mealie_dev"
          user_group: "users"
          admin_group: "proxAdmins"
          auto_redirect: false
    workload:
      main:
        podSpec:
          containers:
            main:
              envFrom:
                - secretRef:
                    name: mealie-oidc
                    expandObjectName: false
    persistence:
      data:
        enabled: true
        storageClass: synology-iscsi-storage
        targetSelector:
          main:
            main:
              mountPath: /app/data
    cnpg:
      main:
        cluster:
          instances: 1
          storage:
            storageClass: synology-iscsi-storage
          walStorage:
            storageClass: synology-iscsi-storage
        