---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mealie
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: mealie
  values:
    persistence:
      data:
        enabled: true
        storageClass: synology-iscsi-storage
        targetSelector:
          main:
            main:
              mountPath: /app/data
    cnpg:
      main:
        cluster:
          instances: 1
          storage:
            storageClass: synology-iscsi-storage
          walStorage:
            storageClass: synology-iscsi-storage
        