---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: imagepullsecrets
  namespace: external-dns
spec:
  type: kv-v2
  mount: secret
  path:  docker/imagepullsecrets
  refreshAfter: 60s
  destination:
    create: true
    name: imagepullsecrets