apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - rook-ceph-external.yaml
  - synology-csi.yaml
  - gotify-token.yaml
  - pdns-apikey.yaml
  - imagepullsecrets.yaml
spec:
  wait: true
  timeout: 2m
  healthCheckExprs:
    - apiVersion: secrets.hashicorp.com/v1beta1
      kind: VaultStaticSecret
      failed: status.conditions.filter(e, e.type == 'SecretSynced').all(e, e.status == 'False')
      current: status.conditions.filter(e, e.type == 'SecretSynced').all(e, e.status == 'True')
    
