apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
  - config-ceph-pvc.yaml
  - assets-ceph-pvc.yaml
  - deployment.yaml
  - service.yaml
  - service-lan.yaml
