apiVersion: v1
kind: Service
metadata:
  name: netbootxyz-lan
  namespace: default
  labels:
    app.kubernetes.io/name: netbootxyz
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: netbootxyz
  ports:
    - name: web
      port: 3000
      targetPort: web
      protocol: TCP
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
    - name: tftp
      port: 69
      targetPort: tftp
      protocol: UDP
