apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: prowlarr
spec:
  interval: 1h
  url: oci://oci.trueforge.org/truecharts/prowlarr
  ref:
    tag: "22.1.0"
  layerSelector:
    mediaType: "application/vnd.cncf.helm.chart.content.v1.tar+gzip"
    operation: copy
