apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: trilium-data-ceph-v2
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: csi-cephfs-sc
