apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
  - ../../base/trilium
  - gateway.yaml
patches:
  - patch: |
      - op: replace
        path: /spec/values/controllers/main/replicas
        value: 1
    target:
      kind: HelmRelease
      name: trilium
  - patch: |
      - op: replace
        path: /metadata/annotations/cert-manager.io~1common-name
        value: trilium.staging.myrobertson.net
      - op: replace
        path: /spec/listeners/0/hostname
        value: trilium.staging.myrobertson.net
      - op: replace
        path: /spec/infrastructure/annotations/external-dns.alpha.kubernetes.io~1hostname
        value: trilium.staging.myrobertson.net
    target:
      kind: Gateway
      name: trilium
  - patch: |
      - op: replace
        path: /spec/hostnames/0
        value: trilium.staging.myrobertson.net
    target:
      kind: HTTPRoute
      name: trilium
  - patch: |
      - op: replace
        path: /spec/resources/requests/storage
        value: 1Gi
    target:
      kind: PersistentVolumeClaim
      name: trilium-data-ceph
