apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: n8n-cnpg
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: n8n
spec:
  instances: 1
  enableSuperuserAccess: false
  storage:
    size: 10Gi
    storageClass: ceph-block
  walStorage:
    size: 2Gi
    storageClass: ceph-block
  managed:
    roles:
      - name: n8n
        login: true
        superuser: false
  bootstrap:
    initdb:
      database: n8n
      owner: n8n