apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: n8n-secret
spec:
  type: kv-v2
  mount: secret
  path: n8n/env/app
  refreshAfter: 60s
  destination:
    create: true
    name: n8n-secret