---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: client-info-secret
  namespace: synology-csi
spec:
  type: kv-v2
  mount: secret
  path: synology/dev/csi-client-info
  refreshAfter: 60s
  destination:
    create: true
    name: client-info-secret
