apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
  - ../../base/mealie
  - httpRoute.yaml
patches:
  - path: mealie-values.yaml
    target:
      kind: HelmRelease
  - patch: |
      - op: replace
        path: /spec/resources/requests/storage
        value: 2Gi
    target:
      kind: PersistentVolumeClaim
      name: mealie-data-files-pvc
  - patch: |
      - op: replace
        path: /spec/path
        value: oidc/prod
    target:
      kind: VaultStaticSecret
      name: mealie-oidc-secret