apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mealie
spec:
  values:
    mealie:
      api:
        general:
          baseUrl: https://mealie.myrobertson.com
    server:
      controllers:
        main:
          replicas: 1
    workload:
      main:
        podSpec:
          containers:
            main:
              env: 
                API_PORT: "10018"
                BASE_URL: https://mealie.myrobertson.com
              envFrom:
                - secretRef:
                    name: mealie-oidc
                    expandObjectName: false
   