apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mealie
spec:
  values:
    mealie:
      api:
        general:
          baseUrl: https://mealie.myrobertson.com
    server:
      controllers:
        main:
          replicas: 1
    workload:
      main:
        podSpec:
          containers:
            main:
              env: 
                API_PORT: "10018"
                BASE_URL: https://mealie.myrobertson.com
                DB_ENGINE: postgres
                POSTGRES_SERVER:
                  secretKeyRef:
                    name: mealie-cnpg-main-app
                    key: host
                POSTGRES_PORT:
                  secretKeyRef:
                    name: mealie-cnpg-main-app
                    key: port
                POSTGRES_DB:
                  secretKeyRef:
                    name: mealie-cnpg-main-app
                    key: dbname
                POSTGRES_USER:
                  secretKeyRef:
                    name: mealie-cnpg-main-app
                    key: username
                POSTGRES_PASSWORD:
                  secretKeyRef:
                    name: mealie-cnpg-main-app
                    key: password
              envFrom:
                - secretRef:
                    name: mealie-oidc
                    expandObjectName: false
   