apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: myrobertson-com-gateway
  namespace: default
  annotations:
    external-dns.alpha.kubernetes.io/target: myrobertson.com
    external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
    cert-manager.io/issuer: letsencrypt-prod
spec:
  gatewayClassName: istio
  listeners:

  - name: auth
    hostname: auth.myrobertson.com
    port: 443
    protocol: HTTPS
    allowedRoutes:
      namespaces:
        from: All
    tls:
      mode: Terminate
      certificateRefs:
      - name: auth-myrobertson-com-cert
        kind: Secret 

  - name: bitwarden
    hostname: bitwarden.myrobertson.com
    port: 443
    protocol: HTTPS
    allowedRoutes:
      namespaces:
        from: All
    tls:
      mode: Terminate
      certificateRefs:
      - name: bitwarden-myrobertson-com-cert
        kind: Secret 

  - name: kermit
    hostname: kermit.myrobertson.com
    port: 443
    protocol: HTTPS
    allowedRoutes:
      namespaces:
        from: All
    tls:
      mode: Terminate
      certificateRefs:
      - name: kermit-myrobertson-com-cert
        kind: Secret 

  - name: gotify
    hostname: gotify.myrobertson.com
    port: 443
    protocol: HTTPS
    allowedRoutes:
      namespaces:
        from: All
    tls:
      mode: Terminate
      certificateRefs:
      - name: gotify-myrobertson-com-cert
        kind: Secret 

  - name: immich
    hostname: immich.myrobertson.com
    port: 443
    protocol: HTTPS
    allowedRoutes:
      namespaces:
        from: All
    tls:
      mode: Terminate
      certificateRefs:
      - name: immich-myrobertson-com-cert
        kind: Secret 
      
  - name: mealie
    hostname: mealie.myrobertson.com
    port: 443
    protocol: HTTPS
    allowedRoutes:
      namespaces:
        from: All
    tls:
      mode: Terminate
      certificateRefs:
      - name: mealie-myrobertson-com-cert
        kind: Secret 

  - name: plex
    hostname: plex.myrobertson.com
    port: 443
    protocol: HTTPS
    allowedRoutes:
      namespaces:
        from: All
    tls:
      mode: Terminate
      certificateRefs:
      - name: plex-myrobertson-com-cert
        kind: Secret   

  - name: radarr
    hostname: radarr.myrobertson.com
    port: 443
    protocol: HTTPS
    allowedRoutes:
      namespaces:
        from: All
    tls:
      mode: Terminate
      certificateRefs:
      - name: radarr-myrobertson-com-cert
        kind: Secret 

  - name: sonarr
    hostname: sonarr.myrobertson.com
    port: 443
    protocol: HTTPS
    allowedRoutes:
      namespaces:
        from: All
    tls:
      mode: Terminate
      certificateRefs:
      - name: sonarr-myrobertson-com-cert
        kind: Secret 

  - name: syncthing
    hostname: syncthing.myrobertson.com
    port: 443
    protocol: HTTPS
    allowedRoutes:
      namespaces:
        from: All
    tls:
      mode: Terminate
      certificateRefs:
      - name: syncthing-myrobertson-com-cert
        kind: Secret 