apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: myrobertson-com-gateway
  namespace: default
  annotations:
    external-dns.alpha.kubernetes.io/target: myrobertson.com
    cert-manager.io/issuer: letsencrypt-prod
spec:
  gatewayClassName: istio
  listeners:
  - name: immich
    hostname: immich.myrobertson.com
    port: 443
    protocol: HTTPS
    allowedRoutes:
      namespaces:
        from: All
    tls:
      mode: Terminate
      certificateRefs:
      - name: immich-myrobertson-com-cert
        kind: Secret 
      
  - name: mealie
    hostname: mealie.myrobertson.com
    port: 443
    protocol: HTTPS
    allowedRoutes:
      namespaces:
        from: All
    tls:
      mode: Terminate
      certificateRefs:
      - name: mealie-myrobertson-com-cert
        kind: Secret 