apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
  - ../../base/trilium
  - httpRoute.yaml
  - ../../base/trilium/migration-secret.yaml
  - ../../base/trilium/pve3-data-seed-job.yaml
