apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ntfy
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: ntfy
  values:
    replicaCount: 1
    ntfy:
      baseURL: http://ntfy.default.svc.cluster.local
      behindProxy: false
    service:
      http:
        type: ClusterIP
        port: 80