apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: ntfy
spec:
  interval: 1h
  url: oci://codeberg.org/wrenix/helm-charts/ntfy
  ref:
    semver: ">=0.5.x"
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy