apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sonarr
spec:
  values:

    sonarr:
      api:
        general:
          baseUrl: https://sonarr.staging.myrobertson.net
    server:
      controllers:
        main:
          replicas: 1
   