---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: code-server
spec:
  releaseName: code-server
  interval: 1h
  chart:
    spec:
      chart: ./ci/helm-chart
      sourceRef:
        kind: GitRepository
        name: code-server
      version: "*"
  values:
    replicaCount: 1
    image:
      repository: codercom/code-server
      tag: "4.114.1"
      pullPolicy: IfNotPresent
    service:
      type: ClusterIP
      port: 8080
    persistence:
      enabled: true
      storageClass: ceph-rook-ssd
      accessMode: ReadWriteOnce
      size: 20Gi
      existingClaim: code-server-data-ceph
    securityContext:
      enabled: true
      fsGroup: 1000
      runAsUser: 1000
    resources:
      requests:
        cpu: 250m
        memory: 512Mi
      limits:
        cpu: 1000m
        memory: 2Gi
    livenessProbe:
      enabled: true
    readinessProbe:
      enabled: true
    ingress:
      enabled: false
