apiVersion: v1
kind: Service
metadata:
  name: external-service-kermit
  namespace: default
spec:
  type: ExternalName
  externalName: kermit.myrobertson.net
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: external-service-kermit-route
  namespace: default
spec:
  parentRefs:
    - name:  myrobertson-com-gateway # Reference your Gateway resource
  hostnames:
    - "kermit.myrobertson.com" # Hostname for which this route applies
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: "/"
      backendRefs:
        - name: external-service-kermit # Reference the ExternalName Service
          port: 5011 # Or the appropriate port for the external service