# Collabora admin credentials for staging Nextcloud Office.
# Vault path should contain:
#   username, password
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: collabora-secret
spec:
  type: kv-v2
  mount: secret
  path: nextcloud/staging/collabora
  refreshAfter: 60s
  destination:
    create: true
    name: collabora-secret
    overwrite: true
