- op: replace
  path: /spec/values/nextcloud/host
  value: cloud.staging.myrobertson.net
- op: replace
  path: /spec/values/nextcloud/extraEnv/1/value
  value: https://cloud.staging.myrobertson.net
- op: add
  path: /spec/values/nextcloud/extraEnv/-
  value:
    name: COLLABORA_PUBLIC_URL
    value: https://office.staging.myrobertson.net
- op: add
  path: /spec/values/nextcloud/extraEnv/-
  value:
    name: COLLABORA_WOPI_URL
    value: http://nextcloud-collabora:9980
- op: add
  path: /spec/values/nextcloud/extraEnv/-
  value:
    name: BUCKET_NAME
    valueFrom:
      configMapKeyRef:
        name: nextcloud-s3-staging
        key: BUCKET_NAME
- op: add
  path: /spec/values/nextcloud/extraEnv/-
  value:
    name: BUCKET_HOST
    valueFrom:
      configMapKeyRef:
        name: nextcloud-s3-staging
        key: BUCKET_HOST
- op: add
  path: /spec/values/nextcloud/extraEnv/-
  value:
    name: BUCKET_PORT
    valueFrom:
      configMapKeyRef:
        name: nextcloud-s3-staging
        key: BUCKET_PORT
- op: add
  path: /spec/values/nextcloud/extraEnv/-
  value:
    name: BUCKET_REGION
    valueFrom:
      configMapKeyRef:
        name: nextcloud-s3-staging
        key: BUCKET_REGION
- op: add
  path: /spec/values/nextcloud/extraEnv/-
  value:
    name: AWS_ACCESS_KEY_ID
    valueFrom:
      secretKeyRef:
        name: nextcloud-s3-staging
        key: AWS_ACCESS_KEY_ID
- op: add
  path: /spec/values/nextcloud/extraEnv/-
  value:
    name: AWS_SECRET_ACCESS_KEY
    valueFrom:
      secretKeyRef:
        name: nextcloud-s3-staging
        key: AWS_SECRET_ACCESS_KEY
- op: add
  path: /spec/values/collabora
  value:
    enabled: true
    collabora:
      aliasgroups:
        - host: "https://cloud.staging.myrobertson.net:443"
      extra_params: "--o:ssl.enable=false --o:ssl.termination=true"
      server_name: office.staging.myrobertson.net
      existingSecret:
        enabled: true
        secretName: collabora-secret
    ingress:
      enabled: false
- op: add
  path: /spec/values/nextcloud/configs/objectstore-s3.config.php
  value: |-
    <?php
    $CONFIG = array(
      'objectstore' => array(
        'class' => '\\OC\\Files\\ObjectStore\\S3',
        'arguments' => array(
          'bucket'         => getenv('BUCKET_NAME'),
          'key'            => getenv('AWS_ACCESS_KEY_ID'),
          'secret'         => getenv('AWS_SECRET_ACCESS_KEY'),
          'hostname'       => getenv('BUCKET_HOST'),
          'port'           => (int)(getenv('BUCKET_PORT') ?: 8080),
          'use_ssl'        => false,
          'use_path_style' => true,
          'region'         => getenv('BUCKET_REGION') ?: 'us-east-1',
        ),
      ),
    );
