---
apiVersion: v1
kind: Namespace
metadata:
  name: vault-secrets-operator-system
  labels:
    toolkit.fluxcd.io/tenant: sre-team
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/warn: privileged
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: vault-secrets-operator
  namespace: vault-secrets-operator-system
spec:
  interval: 24h
  url: https://helm.releases.hashicorp.com
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vault-secrets-operator
  namespace: vault-secrets-operator-system
spec:
  interval: 30m
  chart:
    spec:
      chart: vault-secrets-operator
      sourceRef:
        kind: HelmRepository
        name: vault-secrets-operator
        namespace: vault-secrets-operator-system
      interval: 12h
  values:
    defaultVaultConnection:
      enabled: true
      address: "https://vault.myrobertson.net:8200"
      skipTLSVerify: true
    defaultAuthMethod:
      enabled: true
      mount: staging-kubernetes
      allowed_namespaces:
        - "*"
      kubernetes:
        role: "vault-secrets-operator-role"
        serviceAccountName: "default"
        namespace: "vault-secrets-operator-system"
        tokenAudiences:
          - "https://cp.staging.myrobertson.net:6443"

