apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: istio-system
resources:
  - namespace.yaml
  - repository.yaml
  - release-istio-base.yaml
  - github.com/kubernetes-sigs/gateway-api/releases/download/v1.4.0/standard-install.yaml
  - release-istio-istiod.yaml
  - release-istio-cni.yaml
  - release-istio-ztunnel.yaml