
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: istio-istiod
  namespace: istio-system
spec:
  interval: 30m
  chart:
    spec:
      chart: istiod
      sourceRef:
        kind: HelmRepository
        name: istio-release
        namespace: istio-system
      interval: 12h
  values:
    profile: ambient
    meshConfig:
      accessLogFile: /dev/stdout
      enablePrometheusMerge: true
      extensionProviders:
        - name: authelia
          envoyExtAuthzHttp:
            service: 'authelia.default.svc.cluster.local'
            port: 80
            pathPrefix: '/api/authz/ext-authz/'
            includeRequestHeadersInCheck:
              - 'accept'
              - 'cookie'
              - 'authorization'
              - 'proxy-authorization'
            headersToUpstreamOnAllow:
              - 'remote-*'
              - 'authelia-*'
            includeAdditionalHeadersInCheck:
              X-Forwarded-Proto: '%REQ(:SCHEME)%'
              X-Authelia-URL: 'https://auth.staging.myrobertson.net'
            headersToDownstreamOnDeny:
              - 'set-cookie'
            headersToDownstreamOnAllow:
              - 'set-cookie'
        - name: authelia-net
          envoyExtAuthzHttp:
            service: 'authelia.default.svc.cluster.local'
            port: 80
            pathPrefix: '/api/authz/ext-authz/'
            includeRequestHeadersInCheck:
              - 'accept'
              - 'cookie'
              - 'authorization'
              - 'proxy-authorization'
            headersToUpstreamOnAllow:
              - 'remote-*'
              - 'authelia-*'
            includeAdditionalHeadersInCheck:
              X-Forwarded-Proto: '%REQ(:SCHEME)%'
              X-Authelia-URL: 'https://auth.staging.myrobertson.net'
            headersToDownstreamOnDeny:
              - 'set-cookie'
            headersToDownstreamOnAllow:
              - 'set-cookie'
  
