apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sonarr
spec:
  postRenderers:
    - kustomize:
        patches:
          - target:
              kind: ServiceMonitor
              name: sonarr
            patch: |
              - op: add
                path: /spec/endpoints/0/scrapeTimeout
                value: "60s"
  values:

    sonarr:
      api:
        general:
          baseUrl: https://sonarr.myrobertson.com
    workload:
      main:
        replicas: 1
    persistence:
      media:
        enabled: true
      downloads:
        enabled: true
