apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sonarr
spec:
  values:

    sonarr:
      api:
        general:
          baseUrl: https://sonarr.myrobertson.com
    server:
      controllers:
        main:
          replicas: 0
    workload:
      main:
        replicaCount: 0
   