# apiVersion: kustomize.config.k8s.io/v1beta1
# kind: Kustomization
# namespace: default
# resources:
#   - ../../base/shared_storage
# patches:
#   - patch: |
#       - op: replace
#         path: /spec/resources/requests/storage
#         value: 3Ti
#     target:
#       kind: PersistentVolumeClaim
#       name: downloads
#   - patch: |
#       - op: replace
#         path: /spec/resources/requests/storage
#         value: 5Ti
#     target:
#       kind: PersistentVolumeClaim
#       name: xxx
 