---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: overseerr
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: overseerr
  values:
    persistence:
      config:
        enabled: true
        storageClass: csi-cephfs-sc
        existingClaim: overseerr-config-ceph
        accessModes: ReadWriteMany
        targetSelector:
          main:
            main:
              mountPath: /app/config
            exportarr:
              mountPath: /app/config
              readOnly: true