apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarr-config
spec:
  volumeName: pvc-db01042d-c355-4a3d-baac-a5f0693885dd
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: synology-iscsi-storage
