apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarr-config-ceph
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: csi-cephfs-sc
