apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: radarr
spec:
  values:

    radarr:
      api:
        general:
          baseUrl: https://radarr.myrobertson.com
    workload:
      main:
        replicas: 1
    persistence:
      media:
        enabled: true
      plex:
        enabled: true
      downloads:
        enabled: true
   