apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: radarr
spec:
  postRenderers:
    - kustomize:
        patches:
          - target:
              kind: Deployment
              name: radarr
            patch: |
              apiVersion: apps/v1
              kind: Deployment
              metadata:
                name: radarr
              spec:
                template:
                  spec:
                    containers:
                      - name: radarr
                        resources:
                          requests:
                            memory: 1Gi
                      - name: radarr-exportarr
                        resources:
                          requests:
                            memory: 128Mi
  values:

    radarr:
      api:
        general:
          baseUrl: https://radarr.myrobertson.com
    workload:
      main:
        replicas: 1
    persistence:
      media:
        enabled: true
      plex:
        enabled: true
      downloads:
        enabled: true
