apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: radarr
spec:
  values:

    radarr:
      api:
        general:
          baseUrl: https://radarr.myrobertson.com
    server:
      controllers:
        main:
          replicas: 1
   