apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: volsync
  namespace: default
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: volsync
    namespace: default
  values:
    workload:
      main:
        podSpec:
          hostUsers: true
    volsync:
      api:
        general:
          baseUrl: https://volsync.myrobertson.net
