apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: authelia
spec:
  values:
    configMap:
      storage:
        postgres:
          address: tcp://cluster-authelia-ceph-rw.default.svc.cluster.local:5432
      definitions:
        user_attributes:
          proxmox_groups:
            expression: '"proxAdmins" in groups ? ["proxAdmins"] : []'
      identity_providers:
        oidc:
          enabled: true
          jwks:
            - key_id: main
              algorithm: RS256
              use: sig
              key:
                path: /secrets/internal/identity_providers.oidc.jwks.key
          authorization_policies:
            proxmox_domain_admins:
              default_policy: deny
              rules:
                - subject: 'group:proxAdmins'
                  policy: one_factor
          claims_policies:
            proxmox:
              custom_claims:
                proxmox_groups:
                  attribute: proxmox_groups
          scopes:
            proxmox_groups:
              claims:
                - proxmox_groups
          clients:
            - client_id: mealie_prod
              client_name: Mealie
              client_secret: '$2b$12$G4e2wFGmXCHkQowZZZKOrecbdJik.gd7L5ORyoRVOL7uMZue8SpBW'
              public: false
              authorization_policy: one_factor
              redirect_uris:
                - https://mealie.myrobertson.com/login
              scopes:
                - openid
                - profile
                - email
                - groups
              userinfo_signed_response_alg: none
              token_endpoint_auth_method: client_secret_basic
            - client_id: grafana_prod
              client_name: Grafana Prod
              client_secret: '$2b$12$G4e2wFGmXCHkQowZZZKOrecbdJik.gd7L5ORyoRVOL7uMZue8SpBW'
              public: false
              authorization_policy: one_factor
              redirect_uris:
                - https://grafana.prod.myrobertson.net/login/generic_oauth
              scopes:
                - openid
                - profile
                - email
                - groups
              userinfo_signed_response_alg: none
              token_endpoint_auth_method: client_secret_basic
            - client_id: vikunja_prod
              client_name: Vikunja
              client_secret: '$2b$12$kjY20tnxH8rVDpNccpFqs.fFQYD/F5WkKF8Gr9FOx.z0G5z7qJv4a'
              public: false
              authorization_policy: one_factor
              redirect_uris:
                - https://tasks.myrobertson.com/auth/openid/authelia
              scopes:
                - openid
                - profile
                - email
                - groups
              userinfo_signed_response_alg: none
              token_endpoint_auth_method: client_secret_basic
            - client_id: proxmox_prod
              client_name: Proxmox VE cl0
              client_secret:
                path: /secrets/internal/pve_oidc
              public: false
              authorization_policy: proxmox_domain_admins
              claims_policy: proxmox
              require_pkce: true
              pkce_challenge_method: S256
              redirect_uris:
                - https://cl0.myrobertson.net:8006
                - https://cl0.myrobertson.net:8006/
                - https://pve3.myrobertson.net:8006
                - https://pve3.myrobertson.net:8006/
                - https://pve4.myrobertson.net:8006
                - https://pve4.myrobertson.net:8006/
                - https://pve5.myrobertson.net:8006
                - https://pve5.myrobertson.net:8006/
              scopes:
                - openid
                - profile
                - email
                - groups
                - proxmox_groups
              response_types:
                - code
              grant_types:
                - authorization_code
              access_token_signed_response_alg: none
              userinfo_signed_response_alg: none
              token_endpoint_auth_method: client_secret_basic
            - client_id: pbs_prod
              client_name: Proxmox Backup Server
              client_secret:
                path: /secrets/internal/pbs_oidc
              public: false
              authorization_policy: proxmox_domain_admins
              redirect_uris:
                - https://pbs.myrobertson.net:8007
                - https://pbs.myrobertson.net:8007/
              scopes:
                - openid
                - profile
                - email
              response_types:
                - code
              grant_types:
                - authorization_code
              access_token_signed_response_alg: none
              userinfo_signed_response_alg: none
              token_endpoint_auth_method: client_secret_basic
    secret:
      additionalSecrets: {}
   
