apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: authelia
spec:
  values:
    configMap:
      identity_providers:
        oidc:
          hmac_secret:
            secret_name: authelia-secret
    secret:
      additionalSecrets:
        authelia-secret: {}
   
