apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: authelia-config-ceph-v2
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: csi-cephfs-sc
