apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
  #- change-pvc-permissions.yaml
  - httpRoute.yaml
  - ../../base/authelia
patches:
  # - path: authelia-values.yaml
  #   target:
  #     kind: HelmRelease
  - patch: |
      - op: replace
        path: /spec/path
        value: authelia/prod
    target:
      kind: VaultStaticSecret
      name: authelia-secret