apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
  - ../../base/authelia

  # - path: authelia-values.yaml
  #   target:
  #     kind: HelmRelease
  # - patch: |
  #     - op: replace
  #       path: /spec/path
  #       value: oidc/staging
  #   target:
  #     kind: VaultStaticSecret
  #     name: authelia-oidc-secret