apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
  #- change-pvc-permissions.yaml
  - httpRoute.yaml
  - ../../base/authelia
patches:
  # Uncomment the following patch to perform the Ceph cutover in prod
  # after the Ceph seed/final-sync jobs complete.
  - path: ../../base/authelia/release-ceph-cutover.yaml
    target:
      kind: HelmRelease
      name: authelia
  - patch: |
      - op: replace
        path: /spec/path
        value: authelia/prod
    target:
      kind: VaultStaticSecret
      name: authelia-secret
