apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: cluster-authelia-ceph-daily
  namespace: default
spec:
  schedule: "0 3 * * *"
  backupOwnerReference: self
  cluster:
    name: cluster-authelia-ceph
