---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-p0
  namespace: flux-system
spec:
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/p0
  prune: true
  wait: true
  patches:
    - patch: |
        - op: replace
          path: /spec/mount
          value: staging-kubernetes
        - op: replace
          path: /spec/kubernetes/audiences/0
          value: https://cp.staging.myrobertson.net:6443
      target:
        kind: VaultAuth
        name: default
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-controllers
  namespace: flux-system
spec:
  dependsOn:
    - name: infra-p0
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/controllers
  prune: true
  wait: true
  patches:
    - patch: |
        - op: replace
          path: /spec/path
          value: monitoring/gotify/staging
      target:
        kind: VaultStaticSecret
        name: gotify-token
    - patch: |
        - op: replace
          path: /spec/path
          value: synology/staging/csi-client-info
      target:
        kind: VaultStaticSecret
        name: client-info-secret
    - patch: |
        - op: replace
          path: /spec/values/alertmanager/alertmanagerSpec/storage/volumeClaimTemplate/spec/resources/requests/storage
          value: 1Gi
        - op: replace
          path: /spec/values/prometheus/prometheusSpec/retention
          value: 2d
        - op: replace
          path: /spec/values/prometheus/prometheusSpec/retentionSize
          value: 1GB
        - op: replace
          path: /spec/values/prometheus/storageSpec/volumeClaimTemplate/spec/resources/requests/storage
          value: 2Gi
        - op: replace
          path: /spec/values/grafana/grafana.ini/server/domain
          value: grafana.staging.myrobertson.net
        - op: replace
          path: /spec/values/grafana/grafana.ini/server/root_url
          value: https://grafana.staging.myrobertson.net/
        - op: replace
          path: /spec/values/grafana/grafana.ini/auth.generic_oauth/client_id
          value: grafana_staging
        - op: replace
          path: /spec/values/grafana/grafana.ini/auth.generic_oauth/auth_url
          value: https://auth.staging.myrobertson.net/api/oidc/authorization
        - op: replace
          path: /spec/values/grafana/grafana.ini/auth.generic_oauth/token_url
          value: https://auth.staging.myrobertson.net/api/oidc/token
        - op: replace
          path: /spec/values/grafana/grafana.ini/auth.generic_oauth/api_url
          value: https://auth.staging.myrobertson.net/api/oidc/userinfo
        - op: add
          path: /spec/values/prometheusOperator
          value: {}
        - op: add
          path: /spec/values/prometheusOperator/admissionWebhooks
          value: {}
        - op: add
          path: /spec/values/prometheusOperator/admissionWebhooks/certManager
          value: {}
        - op: replace
          path: /spec/values/prometheusOperator/admissionWebhooks/certManager/enabled
          value: true
      target:
        kind: HelmRelease
        name: kube-prometheus-stack
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-configs
  namespace: flux-system
spec:
  dependsOn:
    - name: infra-controllers
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/configs
  prune: true
  patches:
    - patch: |
        $patch: delete
        apiVersion: monitoring.coreos.com/v1
        kind: PrometheusRule
        metadata:
          name: backup-observability-alerts
      target:
        group: monitoring.coreos.com
        version: v1
        kind: PrometheusRule
        name: backup-observability-alerts
    - patch: |
        $patch: delete
        apiVersion: volsync.backube/v1alpha1
        kind: ReplicationSource
        metadata:
          name: placeholder
      target:
        group: volsync.backube
        version: v1alpha1
        kind: ReplicationSource
    - patch: |
        $patch: delete
        apiVersion: secrets.hashicorp.com/v1beta1
        kind: VaultStaticSecret
        metadata:
          name: restic-config-placeholder
      target:
        group: secrets.hashicorp.com
        version: v1beta1
        kind: VaultStaticSecret
        name: restic-config-.*
    - patch: |
        - op: replace
          path: /spec/path
          value: talos/backup/stage
      target:
        kind: VaultStaticSecret
        name: talos-etcd-backup-credentials
    - patch: |
        - op: replace
          path: /spec/addresses
          value:
            - 10.21.0.64/30
            - 10.21.0.68/32
            - 10.21.0.70/31
            - 10.21.0.72/29
      target:
        kind: IPAddressPool
        name: my-ip-pool
    - patch: |
        - op: replace
          path: /metadata/annotations/cert-manager.io~1common-name
          value: prometheus.staging.myrobertson.net
        - op: replace
          path: /spec/listeners/0/hostname
          value: prometheus.staging.myrobertson.net
        - op: replace
          path: /spec/infrastructure/annotations/external-dns.alpha.kubernetes.io~1hostname
          value: prometheus.staging.myrobertson.net
      target:
        kind: Gateway
        name: prometheus
    - patch: |
        - op: replace
          path: /spec/hostnames/0
          value: prometheus.staging.myrobertson.net
      target:
        kind: HTTPRoute
        name: prometheus
    - patch: |
        - op: replace
          path: /metadata/annotations/cert-manager.io~1common-name
          value: grafana.staging.myrobertson.net
        - op: replace
          path: /spec/listeners/0/hostname
          value: grafana.staging.myrobertson.net
        - op: replace
          path: /spec/infrastructure/annotations/external-dns.alpha.kubernetes.io~1hostname
          value: grafana.staging.myrobertson.net
      target:
        kind: Gateway
        name: grafana
    - patch: |
        - op: replace
          path: /spec/hostnames/0
          value: grafana.staging.myrobertson.net
      target:
        kind: HTTPRoute
        name: grafana
    - patch: |
        - op: replace
          path: /metadata/annotations/cert-manager.io~1common-name
          value: alertmanager.staging.myrobertson.net
        - op: replace
          path: /spec/listeners/0/hostname
          value: alertmanager.staging.myrobertson.net
        - op: replace
          path: /spec/infrastructure/annotations/external-dns.alpha.kubernetes.io~1hostname
          value: alertmanager.staging.myrobertson.net
      target:
        kind: Gateway
        name: alertmanager
    - patch: |
        - op: replace
          path: /spec/hostnames/0
          value: alertmanager.staging.myrobertson.net
      target:
        kind: HTTPRoute
        name: alertmanager
    - patch: |
        - op: replace
          path: /spec/eventMetadata/env
          value: staging
      target:
        kind: Alert
        name: alertmanager
    - patch: |
        - op: replace
          path: /spec/vault/path
          value: pki_int_staging/sign/cluster_ssl_certs
        - op: replace
          path: /spec/vault/auth/kubernetes/mountPath
          value: /v1/auth/staging-kubernetes
        - op: replace
          path: /spec/vault/auth/kubernetes/serviceAccountRef/audiences/0
          value: https://cp.staging.myrobertson.net:6443
      target:
        kind: ClusterIssuer
        name: vault-issuer
    - patch: |
        - op: replace
          path: /spec/vault/path
          value: pki_int_staging/sign/cluster_ssl_certs
        - op: replace
          path: /spec/vault/auth/kubernetes/mountPath
          value: /v1/auth/staging-kubernetes
        - op: replace 
          path: /spec/vault/auth/kubernetes/serviceAccountRef/audiences/0
          value: https://cp.staging.myrobertson.net:6443
      target:
        kind: Issuer
        name: vault-issuer
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-gateway
  namespace: flux-system
spec:
  dependsOn:
    - name: infra-configs
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/gateway/staging
  prune: true
