---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-p0
  namespace: flux-system
spec:
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/p0
  prune: true
  wait: true
  patches:
    - patch: |
        - op: replace
          path: /spec/values/defaultAuthMethod/mount
          value: staging-kubernetes
        - op: replace
          path: /spec/values/defaultAuthMethod/kubernetes/tokenAudiences/0
          value: https://cp.staging.myrobertson.net:6443
      target:
        kind: HelmRelease
        name: vault-secrets-operator
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-controllers
  namespace: flux-system
spec:
  dependsOn:
    - name: infra-p0
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/controllers
  prune: true
  wait: true
  patches:
    - patch: |
        - op: replace
          path: /spec/path
          value: synology/staging/csi-client-info
      target:
        kind: VaultStaticSecret
        name: client-info-secret
    - patch: |
        - op: replace
          path: /spec/values/grafana/grafana.ini/server/domain
          value: grafana.staging.myrobertson.net
        - op: replace
          path: /spec/values/grafana/grafana.ini/server/root_url
          value: https://grafana.staging.myrobertson.net/
      target:
        kind: HelmRelease
        name: kube-prometheus-stack
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-configs
  namespace: flux-system
spec:
  dependsOn:
    - name: infra-controllers
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/configs
  prune: true
  patches:
    - patch: |
        - op: replace
          path: /metadata/annotations/cert-manager.io~1common-name
          value: prometheus.staging.myrobertson.net
        - op: replace
          path: /spec/listeners/0/hostname
          value: prometheus.staging.myrobertson.net
        - op: replace
          path: /spec/infrastructure/annotations/external-dns.alpha.kubernetes.io~1hostname
          value: prometheus.staging.myrobertson.net
      target:
        kind: Gateway
        name: prometheus
    - patch: |
        - op: replace
          path: /spec/hostnames/0
          value: prometheus.staging.myrobertson.net
      target:
        kind: HTTPRoute
        name: prometheus
    - patch: |
        - op: replace
          path: /metadata/annotations/cert-manager.io~1common-name
          value: grafana.staging.myrobertson.net
        - op: replace
          path: /spec/listeners/0/hostname
          value: grafana.staging.myrobertson.net
        - op: replace
          path: /spec/infrastructure/annotations/external-dns.alpha.kubernetes.io~1hostname
          value: grafana.staging.myrobertson.net
      target:
        kind: Gateway
        name: grafana
    - patch: |
        - op: replace
          path: /spec/hostnames/0
          value: grafana.staging.myrobertson.net
      target:
        kind: HTTPRoute
        name: grafana
    - patch: |
        - op: replace
          path: /metadata/annotations/cert-manager.io~1common-name
          value: alertmanager.staging.myrobertson.net
        - op: replace
          path: /spec/listeners/0/hostname
          value: alertmanager.staging.myrobertson.net
        - op: replace
          path: /spec/infrastructure/annotations/external-dns.alpha.kubernetes.io~1hostname
          value: alertmanager.staging.myrobertson.net
      target:
        kind: Gateway
        name: alertmanager
    - patch: |
        - op: replace
          path: /spec/hostnames/0
          value: alertmanager.staging.myrobertson.net
      target:
        kind: HTTPRoute
        name: alertmanager