---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: authelia-config-ceph-backup
spec:
  sourcePVC: authelia-config-ceph
  trigger:
    schedule: "0 */6 * * *"
  restic:
    repository: restic-config-authelia
    pruneIntervalDays: 7
    retain:
      hourly: 0
      daily: 14
      weekly: 8
      monthly: 12
    copyMethod: Clone
    cacheStorageClassName: ceph-filesystem
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: bitwarden-data-ceph-backup
spec:
  sourcePVC: bitwarden-data-ceph
  trigger:
    schedule: "55 */6 * * *"
  restic:
    repository: restic-config-bitwarden
    pruneIntervalDays: 7
    retain:
      hourly: 0
      daily: 14
      weekly: 8
      monthly: 12
    copyMethod: Clone
    cacheStorageClassName: ceph-filesystem
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: gotify-data-ceph-backup
spec:
  sourcePVC: gotify-data-ceph
  trigger:
    schedule: "35 */6 * * *"
  restic:
    repository: restic-config-gotify
    pruneIntervalDays: 7
    retain:
      hourly: 0
      daily: 14
      weekly: 8
      monthly: 12
    copyMethod: Clone
    cacheStorageClassName: ceph-filesystem
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: netbootxyz-config-ceph-backup
spec:
  sourcePVC: netbootxyz-config-ceph
  trigger:
    schedule: "27 */6 * * *"
  restic:
    repository: restic-config-netbootxyz-config
    pruneIntervalDays: 7
    retain:
      hourly: 0
      daily: 14
      weekly: 8
      monthly: 12
    copyMethod: Clone
    cacheStorageClassName: ceph-filesystem
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: netbootxyz-assets-ceph-backup
spec:
  sourcePVC: netbootxyz-assets-ceph
  trigger:
    schedule: "28 */6 * * *"
  restic:
    repository: restic-config-netbootxyz-assets
    pruneIntervalDays: 7
    retain:
      hourly: 0
      daily: 14
      weekly: 8
      monthly: 12
    copyMethod: Clone
    cacheStorageClassName: ceph-filesystem
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: cluster-authelia-ceph-1-backup
spec:
  sourcePVC: cluster-authelia-ceph-1
  trigger:
    schedule: "32 */6 * * *"
  restic:
    repository: restic-config-authelia-cnpg-data
    pruneIntervalDays: 7
    retain:
      hourly: 0
      daily: 14
      weekly: 8
      monthly: 12
    copyMethod: Clone
    cacheStorageClassName: ceph-filesystem
    moverSecurityContext:
      runAsUser: 26
      runAsGroup: 26
      fsGroup: 26
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: immich-data-files-pvc-ceph-backup
spec:
  sourcePVC: immich-data-files-pvc-ceph
  trigger:
    schedule: "10 */6 * * *"
  restic:
    repository: restic-config-immich
    pruneIntervalDays: 7
    retain:
      hourly: 0
      daily: 14
      weekly: 8
      monthly: 12
    copyMethod: Clone
    cacheStorageClassName: ceph-filesystem
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: cluster-immich-ceph-1-backup
spec:
  sourcePVC: cluster-immich-ceph-1
  trigger:
    schedule: "12 */6 * * *"
  restic:
    repository: restic-config-immich-cnpg-data
    pruneIntervalDays: 7
    retain:
      hourly: 0
      daily: 14
      weekly: 8
      monthly: 12
    copyMethod: Clone
    cacheStorageClassName: ceph-filesystem
    moverSecurityContext:
      runAsUser: 26
      runAsGroup: 26
      fsGroup: 26
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: lidarr-config-ceph-backup
spec:
  sourcePVC: lidarr-config-ceph
  trigger:
    schedule: "20 */6 * * *"
  restic:
    repository: restic-config-lidarr
    pruneIntervalDays: 7
    retain:
      hourly: 0
      daily: 14
      weekly: 8
      monthly: 12
    copyMethod: Clone
    cacheStorageClassName: ceph-filesystem
    moverSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: mealie-data-ceph-backup
spec:
  sourcePVC: mealie-data-ceph
  trigger:
    schedule: "30 */6 * * *"
  restic:
    repository: restic-config-mealie
    pruneIntervalDays: 7
    retain:
      hourly: 0
      daily: 14
      weekly: 8
      monthly: 12
    copyMethod: Clone
    cacheStorageClassName: ceph-filesystem
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: mealie-cnpg-main-1-backup
spec:
  sourcePVC: mealie-cnpg-main-1
  trigger:
    schedule: "34 */6 * * *"
  restic:
    repository: restic-config-mealie-cnpg-data
    pruneIntervalDays: 7
    retain:
      hourly: 0
      daily: 14
      weekly: 8
      monthly: 12
    copyMethod: Clone
    cacheStorageClassName: ceph-filesystem
    moverSecurityContext:
      runAsUser: 26
      runAsGroup: 26
      fsGroup: 26
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: mealie-cnpg-main-1-wal-backup
spec:
  sourcePVC: mealie-cnpg-main-1-wal
  trigger:
    schedule: "44 */6 * * *"
  restic:
    repository: restic-config-mealie-cnpg-wal
    pruneIntervalDays: 7
    retain:
      hourly: 0
      daily: 14
      weekly: 8
      monthly: 12
    copyMethod: Clone
    cacheStorageClassName: ceph-filesystem
    moverSecurityContext:
      runAsUser: 26
      runAsGroup: 26
      fsGroup: 26
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: overseerr-config-ceph-backup
spec:
  sourcePVC: overseerr-config-ceph
  trigger:
    schedule: "40 */6 * * *"
  restic:
    repository: restic-config-overseerr
    pruneIntervalDays: 7
    retain:
      hourly: 0
      daily: 14
      weekly: 8
      monthly: 12
    copyMethod: Clone
    cacheStorageClassName: ceph-filesystem
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: prowlarr-config-ceph-backup
spec:
  sourcePVC: prowlarr-config-ceph
  trigger:
    schedule: "50 */6 * * *"
  restic:
    repository: restic-config-prowlarr
    pruneIntervalDays: 7
    retain:
      hourly: 0
      daily: 14
      weekly: 8
      monthly: 12
    copyMethod: Clone
    cacheStorageClassName: ceph-filesystem
    moverSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: radarr-config-ceph-backup
spec:
  sourcePVC: radarr-config-ceph
  trigger:
    schedule: "5 */6 * * *"
  restic:
    repository: restic-config-radarr
    pruneIntervalDays: 7
    retain:
      hourly: 0
      daily: 14
      weekly: 8
      monthly: 12
    copyMethod: Clone
    cacheStorageClassName: ceph-filesystem
    moverSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: sonarr-config-ceph-backup
spec:
  sourcePVC: sonarr-config-ceph
  trigger:
    schedule: "15 */6 * * *"
  restic:
    repository: restic-config-sonarr
    pruneIntervalDays: 7
    retain:
      hourly: 0
      daily: 14
      weekly: 8
      monthly: 12
    copyMethod: Clone
    cacheStorageClassName: ceph-filesystem
    moverSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: tautulli-config-ceph-backup
spec:
  sourcePVC: tautulli-config-ceph
  trigger:
    schedule: "45 */6 * * *"
  restic:
    repository: restic-config-tautulli
    pruneIntervalDays: 7
    retain:
      hourly: 0
      daily: 14
      weekly: 8
      monthly: 12
    copyMethod: Clone
    cacheStorageClassName: ceph-filesystem
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: syncthing-config-ceph-backup
spec:
  sourcePVC: syncthing-config-ceph
  trigger:
    schedule: "25 */6 * * *"
  restic:
    repository: restic-config-syncthing
    pruneIntervalDays: 7
    retain:
      hourly: 0
      daily: 14
      weekly: 8
      monthly: 12
    copyMethod: Clone
    cacheStorageClassName: ceph-filesystem
    moverSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
