---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: restic-config-authelia
spec:
  type: kv-v2
  mount: secret
  path: volsync/prod/authelia-config-ceph
  refreshAfter: 60s
  destination:
    create: true
    name: restic-config-authelia
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: restic-config-authelia-cnpg-data
spec:
  type: kv-v2
  mount: secret
  path: volsync/prod/cluster-authelia-ceph-1
  refreshAfter: 60s
  destination:
    create: true
    name: restic-config-authelia-cnpg-data
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: restic-config-bitwarden
spec:
  type: kv-v2
  mount: secret
  path: volsync/prod/bitwarden-data-ceph
  refreshAfter: 60s
  destination:
    create: true
    name: restic-config-bitwarden
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: restic-config-immich
spec:
  type: kv-v2
  mount: secret
  path: volsync/prod/immich-data-files-pvc-ceph
  refreshAfter: 60s
  destination:
    create: true
    name: restic-config-immich
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: restic-config-immich-cnpg-data
spec:
  type: kv-v2
  mount: secret
  path: volsync/prod/cluster-immich-ceph-1
  refreshAfter: 60s
  destination:
    create: true
    name: restic-config-immich-cnpg-data
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: restic-config-lidarr
spec:
  type: kv-v2
  mount: secret
  path: volsync/prod/lidarr-config-ceph
  refreshAfter: 60s
  destination:
    create: true
    name: restic-config-lidarr
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: restic-config-lidarr-data
spec:
  type: kv-v2
  mount: secret
  path: volsync/prod/lidarr-data-files-pvc
  refreshAfter: 60s
  destination:
    create: true
    name: restic-config-lidarr-data
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: restic-config-mealie
spec:
  type: kv-v2
  mount: secret
  path: volsync/prod/mealie-data-ceph
  refreshAfter: 60s
  destination:
    create: true
    name: restic-config-mealie
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: restic-config-mealie-cnpg-data
spec:
  type: kv-v2
  mount: secret
  path: volsync/prod/mealie-cnpg-main-1
  refreshAfter: 60s
  destination:
    create: true
    name: restic-config-mealie-cnpg-data
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: restic-config-mealie-cnpg-wal
spec:
  type: kv-v2
  mount: secret
  path: volsync/prod/mealie-cnpg-main-1-wal
  refreshAfter: 60s
  destination:
    create: true
    name: restic-config-mealie-cnpg-wal
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: restic-config-overseerr
spec:
  type: kv-v2
  mount: secret
  path: volsync/prod/overseerr-config-ceph
  refreshAfter: 60s
  destination:
    create: true
    name: restic-config-overseerr
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: restic-config-overseerr-data
spec:
  type: kv-v2
  mount: secret
  path: volsync/prod/overseerr-data-files-pvc
  refreshAfter: 60s
  destination:
    create: true
    name: restic-config-overseerr-data
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: restic-config-prowlarr
spec:
  type: kv-v2
  mount: secret
  path: volsync/prod/prowlarr-config-ceph
  refreshAfter: 60s
  destination:
    create: true
    name: restic-config-prowlarr
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: restic-config-prowlarr-data
spec:
  type: kv-v2
  mount: secret
  path: volsync/prod/prowlarr-data-files-pvc
  refreshAfter: 60s
  destination:
    create: true
    name: restic-config-prowlarr-data
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: restic-config-radarr
spec:
  type: kv-v2
  mount: secret
  path: volsync/prod/radarr-config-ceph
  refreshAfter: 60s
  destination:
    create: true
    name: restic-config-radarr
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: restic-config-radarr-data
spec:
  type: kv-v2
  mount: secret
  path: volsync/prod/radarr-data-files-pvc
  refreshAfter: 60s
  destination:
    create: true
    name: restic-config-radarr-data
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: restic-config-sonarr
spec:
  type: kv-v2
  mount: secret
  path: volsync/prod/sonarr-config-ceph
  refreshAfter: 60s
  destination:
    create: true
    name: restic-config-sonarr
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: restic-config-sonarr-data
spec:
  type: kv-v2
  mount: secret
  path: volsync/prod/sonarr-data-files-pvc
  refreshAfter: 60s
  destination:
    create: true
    name: restic-config-sonarr-data
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: restic-config-syncthing
spec:
  type: kv-v2
  mount: secret
  path: volsync/prod/syncthing-config-ceph
  refreshAfter: 60s
  destination:
    create: true
    name: restic-config-syncthing
