---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: restic-config-authelia
  annotations:
    volsync.myrobertson.net/repository-name: authelia-config-ceph
spec:
  type: kv-v2
  mount: secret
  path: backblaze/k8s/prod/volsync
  refreshAfter: 60s
  destination:
    create: true
    name: restic-config-authelia
    transformation:
      excludeRaw: true
      transformationRefs:
        - name: volsync-backblaze-b2
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: restic-config-bitwarden
  annotations:
    volsync.myrobertson.net/repository-name: bitwarden-data-ceph
spec:
  type: kv-v2
  mount: secret
  path: backblaze/k8s/prod/volsync
  refreshAfter: 60s
  destination:
    create: true
    name: restic-config-bitwarden
    transformation:
      excludeRaw: true
      transformationRefs:
        - name: volsync-backblaze-b2
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: restic-config-gotify
  annotations:
    volsync.myrobertson.net/repository-name: gotify-data-ceph
spec:
  type: kv-v2
  mount: secret
  path: backblaze/k8s/prod/volsync
  refreshAfter: 60s
  destination:
    create: true
    name: restic-config-gotify
    transformation:
      excludeRaw: true
      transformationRefs:
        - name: volsync-backblaze-b2
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: restic-config-tautulli
  annotations:
    volsync.myrobertson.net/repository-name: tautulli-config-ceph
spec:
  type: kv-v2
  mount: secret
  path: backblaze/k8s/prod/volsync
  refreshAfter: 60s
  destination:
    create: true
    name: restic-config-tautulli
    transformation:
      excludeRaw: true
      transformationRefs:
        - name: volsync-backblaze-b2
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: restic-config-netbootxyz-config
  annotations:
    volsync.myrobertson.net/repository-name: netbootxyz-config-ceph
spec:
  type: kv-v2
  mount: secret
  path: backblaze/k8s/prod/volsync
  refreshAfter: 60s
  destination:
    create: true
    name: restic-config-netbootxyz-config
    transformation:
      excludeRaw: true
      transformationRefs:
        - name: volsync-backblaze-b2
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: restic-config-netbootxyz-assets
  annotations:
    volsync.myrobertson.net/repository-name: netbootxyz-assets-ceph
spec:
  type: kv-v2
  mount: secret
  path: backblaze/k8s/prod/volsync
  refreshAfter: 60s
  destination:
    create: true
    name: restic-config-netbootxyz-assets
    transformation:
      excludeRaw: true
      transformationRefs:
        - name: volsync-backblaze-b2
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: restic-config-immich
  annotations:
    volsync.myrobertson.net/repository-name: immich-data-files-pvc-ceph
spec:
  type: kv-v2
  mount: secret
  path: backblaze/k8s/prod/volsync
  refreshAfter: 60s
  destination:
    create: true
    name: restic-config-immich
    transformation:
      excludeRaw: true
      transformationRefs:
        - name: volsync-backblaze-b2
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: restic-config-lidarr
  annotations:
    volsync.myrobertson.net/repository-name: lidarr-config-ceph
spec:
  type: kv-v2
  mount: secret
  path: backblaze/k8s/prod/volsync
  refreshAfter: 60s
  destination:
    create: true
    name: restic-config-lidarr
    transformation:
      excludeRaw: true
      transformationRefs:
        - name: volsync-backblaze-b2
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: restic-config-lidarr-data
  annotations:
    volsync.myrobertson.net/repository-name: lidarr-data-files-pvc
spec:
  type: kv-v2
  mount: secret
  path: backblaze/k8s/prod/volsync
  refreshAfter: 60s
  destination:
    create: true
    name: restic-config-lidarr-data
    transformation:
      excludeRaw: true
      transformationRefs:
        - name: volsync-backblaze-b2
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: restic-config-mealie
  annotations:
    volsync.myrobertson.net/repository-name: mealie-data-ceph
spec:
  type: kv-v2
  mount: secret
  path: backblaze/k8s/prod/volsync
  refreshAfter: 60s
  destination:
    create: true
    name: restic-config-mealie
    transformation:
      excludeRaw: true
      transformationRefs:
        - name: volsync-backblaze-b2
---
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: restic-config-overseerr
  annotations:
    volsync.myrobertson.net/repository-name: overseerr-config-ceph
spec:
  type: kv-v2
  mount: secret
  path: backblaze/k8s/prod/volsync
  refreshAfter: 60s
  destination:
    create: true
    name: restic-config-overseerr
    transformation:
      excludeRaw: true
      transformationRefs:
        - name: volsync-backblaze-b2
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: restic-config-overseerr-data
  annotations:
    volsync.myrobertson.net/repository-name: overseerr-data-files-pvc
spec:
  type: kv-v2
  mount: secret
  path: backblaze/k8s/prod/volsync
  refreshAfter: 60s
  destination:
    create: true
    name: restic-config-overseerr-data
    transformation:
      excludeRaw: true
      transformationRefs:
        - name: volsync-backblaze-b2
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: restic-config-prowlarr
  annotations:
    volsync.myrobertson.net/repository-name: prowlarr-config-ceph
spec:
  type: kv-v2
  mount: secret
  path: backblaze/k8s/prod/volsync
  refreshAfter: 60s
  destination:
    create: true
    name: restic-config-prowlarr
    transformation:
      excludeRaw: true
      transformationRefs:
        - name: volsync-backblaze-b2
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: restic-config-prowlarr-data
  annotations:
    volsync.myrobertson.net/repository-name: prowlarr-data-files-pvc
spec:
  type: kv-v2
  mount: secret
  path: backblaze/k8s/prod/volsync
  refreshAfter: 60s
  destination:
    create: true
    name: restic-config-prowlarr-data
    transformation:
      excludeRaw: true
      transformationRefs:
        - name: volsync-backblaze-b2
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: restic-config-radarr
  annotations:
    volsync.myrobertson.net/repository-name: radarr-config-ceph
spec:
  type: kv-v2
  mount: secret
  path: backblaze/k8s/prod/volsync
  refreshAfter: 60s
  destination:
    create: true
    name: restic-config-radarr
    transformation:
      excludeRaw: true
      transformationRefs:
        - name: volsync-backblaze-b2
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: restic-config-radarr-data
  annotations:
    volsync.myrobertson.net/repository-name: radarr-data-files-pvc
spec:
  type: kv-v2
  mount: secret
  path: backblaze/k8s/prod/volsync
  refreshAfter: 60s
  destination:
    create: true
    name: restic-config-radarr-data
    transformation:
      excludeRaw: true
      transformationRefs:
        - name: volsync-backblaze-b2
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: restic-config-sonarr
  annotations:
    volsync.myrobertson.net/repository-name: sonarr-config-ceph
spec:
  type: kv-v2
  mount: secret
  path: backblaze/k8s/prod/volsync
  refreshAfter: 60s
  destination:
    create: true
    name: restic-config-sonarr
    transformation:
      excludeRaw: true
      transformationRefs:
        - name: volsync-backblaze-b2
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: restic-config-sonarr-data
  annotations:
    volsync.myrobertson.net/repository-name: sonarr-data-files-pvc
spec:
  type: kv-v2
  mount: secret
  path: backblaze/k8s/prod/volsync
  refreshAfter: 60s
  destination:
    create: true
    name: restic-config-sonarr-data
    transformation:
      excludeRaw: true
      transformationRefs:
        - name: volsync-backblaze-b2
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: restic-config-syncthing
  annotations:
    volsync.myrobertson.net/repository-name: syncthing-config-ceph
spec:
  type: kv-v2
  mount: secret
  path: backblaze/k8s/prod/volsync
  refreshAfter: 60s
  destination:
    create: true
    name: restic-config-syncthing
    transformation:
      excludeRaw: true
      transformationRefs:
        - name: volsync-backblaze-b2
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: restic-config-trilium
  annotations:
    volsync.myrobertson.net/repository-name: trilium-data-ceph
spec:
  type: kv-v2
  mount: secret
  path: backblaze/k8s/prod/volsync
  refreshAfter: 60s
  destination:
    create: true
    name: restic-config-trilium
    transformation:
      excludeRaw: true
      transformationRefs:
        - name: volsync-backblaze-b2
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: restic-config-plex
  annotations:
    volsync.myrobertson.net/repository-name: plex-config-ceph
spec:
  type: kv-v2
  mount: secret
  path: backblaze/k8s/prod/volsync
  refreshAfter: 60s
  destination:
    create: true
    name: restic-config-plex
    transformation:
      excludeRaw: true
      transformationRefs:
        - name: volsync-backblaze-b2
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: restic-config-code-server
  annotations:
    volsync.myrobertson.net/repository-name: code-server-data-ceph
spec:
  type: kv-v2
  mount: secret
  path: backblaze/k8s/prod/volsync
  refreshAfter: 60s
  destination:
    create: true
    name: restic-config-code-server
    transformation:
      excludeRaw: true
      transformationRefs:
        - name: volsync-backblaze-b2
