apiVersion: secrets.hashicorp.com/v1beta1
kind: SecretTransformation
metadata:
  name: volsync-backblaze-b2
spec:
  excludes:
    - .*
  templates:
    AWS_ACCESS_KEY_ID:
      text: '{{- template "awsAccessKeyId" . -}}'
    AWS_SECRET_ACCESS_KEY:
      text: '{{- template "awsSecretAccessKey" . -}}'
    AWS_REGION:
      text: '{{- template "awsRegion" . -}}'
    AWS_DEFAULT_REGION:
      text: '{{- template "awsRegion" . -}}'
    RESTIC_PASSWORD:
      text: '{{- template "resticPassword" . -}}'
    RESTIC_REPOSITORY:
      text: '{{- template "resticRepository" . -}}'
  sourceTemplates:
    - name: helpers
      text: |
        {{- define "awsAccessKeyId" -}}
        {{- coalesce
              (get .Secrets "AWS_ACCESS_KEY_ID")
              (get .Secrets "applicationKeyId")
              (get .Secrets "APPLICATION_KEY_ID")
              (get .Secrets "BACKBLAZE_APPLICATION_KEY_ID")
              (get .Secrets "B2_APPLICATION_KEY_ID")
              (get .Secrets "keyID")
              (get .Secrets "keyId")
        -}}
        {{- end -}}

        {{- define "awsSecretAccessKey" -}}
        {{- coalesce
              (get .Secrets "AWS_SECRET_ACCESS_KEY")
              (get .Secrets "applicationKey")
              (get .Secrets "APPLICATION_KEY")
              (get .Secrets "BACKBLAZE_APPLICATION_KEY")
              (get .Secrets "B2_APPLICATION_KEY")
        -}}
        {{- end -}}

        {{- define "awsRegion" -}}
        {{- coalesce
              (get .Secrets "AWS_REGION")
              (get .Secrets "AWS_DEFAULT_REGION")
              (get .Secrets "S3_REGION")
              (get .Secrets "BACKBLAZE_REGION")
              "us-west-002"
        -}}
        {{- end -}}

        {{- define "resticPassword" -}}
        {{- coalesce
              (get .Secrets "RESTIC_PASSWORD")
              (get .Secrets "resticPassword")
              (get .Secrets "restic_password")
              (get .Secrets "B2_RESTIC_PASSWORD")
        -}}
        {{- end -}}

        {{- define "resticRepository" -}}
        {{- printf "s3:https://%s/%s/volsync/default/%s"
              (coalesce
                (get .Secrets "S3_ENDPOINT")
                (get .Secrets "AWS_ENDPOINT")
                (get .Secrets "B2_ENDPOINT")
                "s3.us-west-002.backblazeb2.com")
              (coalesce
                (get .Secrets "S3_BUCKET")
                (get .Secrets "B2_BUCKET")
                (get .Secrets "BUCKET_NAME")
                "myrobertson-k8s-prod-volsync")
              (get .Annotations "volsync.myrobertson.net/repository-name")
        -}}
        {{- end -}}
