apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: overseerr
spec:
  values:

    overseerr:
      api:
        general:
          baseUrl: https://overseerr.staging.myrobertson.net
    server:
      controllers:
        main:
          replicas: 1
   