apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
  - ../../base/radarr
  - gateway.yaml
patches:
  - path: radarr-values.yaml
    target:
      kind: HelmRelease
  - patch: |
      - op: replace
        path: /metadata/annotations/cert-manager.io~1common-name
        value: radarr.staging.myrobertson.net
      - op: replace
        path: /spec/listeners/0/hostname
        value: radarr.staging.myrobertson.net
      - op: replace
        path: /spec/infrastructure/annotations/external-dns.alpha.kubernetes.io~1hostname
        value: radarr.staging.myrobertson.net
    target:
      kind: Gateway
      name: radarr
  - patch: |
      - op: replace
        path: /spec/hostnames/0
        value: radarr.staging.myrobertson.net
    target:
      kind: HTTPRoute
      name: radarr
  - patch: |
      - op: replace
        path: /spec/resources/requests/storage
        value: 2Gi
    target:
      kind: PersistentVolumeClaim
      name: radarr-data-files-pvc
  - patch: |
      - op: replace
        path: /spec/path
        value: oidc/staging
    target:
      kind: VaultStaticSecret
      name: radarr-oidc-secret