apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: cnpg-backup-s3
  namespace: guacamole
spec:
  type: kv-v2
  mount: secret
  path: backblaze/k8s/prod/volsync
  refreshAfter: 60s
  destination:
    create: true
    name: cnpg-backup-s3
    transformation:
      excludeRaw: true
      transformationRefs:
        - name: cnpg-backblaze-b2

