apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: guacamole
resources:
  - ../../base/guacamole
  - httpRoute.yaml
  - postgres-scheduled-backup.yaml
  - cnpg-backup-secret.yaml
patches:
  - path: patch-env.yaml
    target:
      kind: Deployment
      name: guacamole
  - patch: |
      - op: add
        path: /spec/backup
        value:
          barmanObjectStore:
            destinationPath: s3://myrobertson-k8s-prod-volsync/cnpg/guacamole-cnpg
            endpointURL: https://s3.us-west-002.backblazeb2.com
            wal:
              compression: gzip
              encryption: AES256
            data:
              compression: gzip
              encryption: AES256
            s3Credentials:
              accessKeyId:
                name: cnpg-backup-s3
                key: AWS_ACCESS_KEY_ID
              secretAccessKey:
                name: cnpg-backup-s3
                key: AWS_SECRET_ACCESS_KEY
          retentionPolicy: 30d
    target:
      kind: Cluster
      name: guacamole-cnpg
  - patch: |
      apiVersion: postgresql.cnpg.io/v1
      kind: Cluster
      metadata:
        name: guacamole-cnpg
        annotations:
          cnpg.io/skipEmptyWalArchiveCheck: enabled
    target:
      kind: Cluster
      name: guacamole-cnpg

