apiVersion: apps/v1
kind: Deployment
metadata:
  name: guacamole
spec:
  template:
    spec:
      containers:
        - name: guacamole
          env:
            - name: OPENID_CLIENT_ID
              value: guacamole_prod
            - name: OPENID_ISSUER
              value: https://sso.myrobertson.com/realms/homelab
            - name: OPENID_AUTHORIZATION_ENDPOINT
              value: https://sso.myrobertson.com/realms/homelab/protocol/openid-connect/auth
            - name: OPENID_JWKS_ENDPOINT
              value: https://sso.myrobertson.com/realms/homelab/protocol/openid-connect/certs
            - name: OPENID_REDIRECT_URI
              value: https://rdp.myrobertson.com
