apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: guacamole-cnpg-daily
  namespace: guacamole
spec:
  schedule: "0 30 3 * * *"
  backupOwnerReference: self
  cluster:
    name: guacamole-cnpg

