---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    toolkit.fluxcd.io/tenant: sre-team
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/warn: privileged
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: monitoring-tokenreview
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
  - kind: ServiceAccount
    name: default
    namespace: monitoring
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:
  interval: 24h
  url: https://prometheus-community.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:
  interval: 30m
  chart:
    spec:
      chart: kube-prometheus-stack
      sourceRef:
        kind: HelmRepository
        name: kube-prometheus-stack
        namespace: monitoring
      interval: 12h
  valuesFrom:
    - kind: ConfigMap
      name: flux-kube-state-metrics-config
      namespace: monitoring
      valuesKey: kube-state-metrics-config.yaml
  values:
    alertmanager:
      config:
        global:
          resolve_timeout: 5m
        route:
          receiver: 'gotify-receiver'
          group_by: ['alertname']
          group_wait: 30s
          group_interval: 5m
          repeat_interval: 12h
          routes:
            - match:
                severity: critical
              receiver: gotify-receiver
        receivers:
          - name: 'gotify-receiver'
            webhook_configs:
              - url: 'http://gotify-bridge.monitoring.svc.cluster.local/gotify_webhook'
                send_resolved: true
      alertmanagerSpec:
        storage:
          volumeClaimTemplate:
            spec:
              accessModes: ["ReadWriteMany"]
              resources:
                requests:
                  storage: 10Gi
              storageClassName: synology-iscsi-storage-delete

    kubeScheduler:
      serviceMonitor:
        ## Skip TLS certificate validation when scraping
        insecureSkipVerify: true

    kubeControllerManager:
      serviceMonitor:
        ## Skip TLS certificate validation when scraping
        insecureSkipVerify: true

    kubeEtcd:
      enabled: true
      service:
        selector:
          k8s-app: kube-controller-manager 
        enabled: true
        port: 2381
        targetPort: 2381
      serviceMonitor:
        relabelings:   # Add nodename label
          - sourceLabels: [__meta_kubernetes_pod_node_name]
            separator: ;
            regex: ^(.*)$
            targetLabel: nodename
            replacement: $1
            action: replace
        metricRelabelings:   # Remove pod label
          - action: labeldrop
            regex: pod

    prometheus:
      prometheusSpec:
        podMonitorSelectorNilUsesHelmValues: false
        serviceMonitorSelectorNilUsesHelmValues: false
      storageSpec:
        volumeClaimTemplate:
          spec:
            accessModes: ["ReadWriteMany"]
            resources:
              requests:
                storage: 50Gi
            storageClassName: synology-iscsi-storage-delete
    
