apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: lidarr
spec:
  values:

    lidarr:
      api:
        general:
          baseUrl: https://lidarr.myrobertson.com
    workload:
      main:
        replicas: 0
    persistence:
      media:
        enabled: true
      downloads:
        enabled: true
   