apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: restic-config-nextcloud
  annotations:
    volsync.myrobertson.net/repository-name: nextcloud-data-pvc-ceph
spec:
  type: kv-v2
  mount: secret
  path: backblaze/k8s/prod/volsync
  refreshAfter: 60s
  destination:
    create: true
    name: restic-config-nextcloud
    transformation:
      excludeRaw: true
      transformationRefs:
        - name: volsync-backblaze-b2
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: restic-config-nextcloud-cnpg-data
  annotations:
    volsync.myrobertson.net/repository-name: nextcloud-cnpg-1
spec:
  type: kv-v2
  mount: secret
  path: backblaze/k8s/prod/volsync
  refreshAfter: 60s
  destination:
    create: true
    name: restic-config-nextcloud-cnpg-data
    transformation:
      excludeRaw: true
      transformationRefs:
        - name: volsync-backblaze-b2
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: restic-config-nextcloud-cnpg-wal
  annotations:
    volsync.myrobertson.net/repository-name: nextcloud-cnpg-1-wal
spec:
  type: kv-v2
  mount: secret
  path: backblaze/k8s/prod/volsync
  refreshAfter: 60s
  destination:
    create: true
    name: restic-config-nextcloud-cnpg-wal
    transformation:
      excludeRaw: true
      transformationRefs:
        - name: volsync-backblaze-b2
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: nextcloud-data-pvc-ceph-backup
spec:
  sourcePVC: nextcloud-data-pvc-ceph-v2
  paused: false
  trigger:
    schedule: "21 * * * *"
  restic:
    repository: restic-config-nextcloud
    pruneIntervalDays: 1
    retain:
      hourly: 4
      daily: 0
      weekly: 0
      monthly: 0
      yearly: 0
    copyMethod: Direct
    cacheStorageClassName: csi-cephfs-sc
    moverResources:
      requests:
        cpu: "500m"
        memory: "2Gi"
      limits:
        cpu: "4"
        memory: "8Gi"
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: nextcloud-cnpg-data-backup
spec:
  sourcePVC: nextcloud-cnpg-1
  paused: false
  trigger:
    schedule: "22 * * * *"
  restic:
    repository: restic-config-nextcloud-cnpg-data
    pruneIntervalDays: 1
    retain:
      hourly: 4
      daily: 0
      weekly: 0
      monthly: 0
      yearly: 0
    copyMethod: Direct
    cacheStorageClassName: csi-cephfs-sc
    moverSecurityContext:
      runAsUser: 26
      runAsGroup: 26
      fsGroup: 26
    moverResources:
      requests:
        cpu: "500m"
        memory: "1Gi"
      limits:
        cpu: "2"
        memory: "4Gi"
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: nextcloud-cnpg-wal-backup
spec:
  sourcePVC: nextcloud-cnpg-1-wal
  paused: false
  trigger:
    schedule: "23 * * * *"
  restic:
    repository: restic-config-nextcloud-cnpg-wal
    pruneIntervalDays: 1
    retain:
      hourly: 4
      daily: 0
      weekly: 0
      monthly: 0
      yearly: 0
    copyMethod: Direct
    cacheStorageClassName: csi-cephfs-sc
    moverSecurityContext:
      runAsUser: 26
      runAsGroup: 26
      fsGroup: 26
    moverResources:
      requests:
        cpu: "500m"
        memory: "1Gi"
      limits:
        cpu: "2"
        memory: "4Gi"
