apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: collabora-secret
  namespace: default
spec:
  type: kv-v2
  mount: secret
  path: nextcloud/prod/collabora
  destination:
    name: collabora-secret
    create: true
  refreshAfter: 1h
