- op: add
  path: /spec/values/nextcloud/objectStore
  value:
    s3:
      enabled: true
      existingSecret: nextcloud-s3-secret
      region: us-east-1
      usePathStyle: false
      ssl: true
      autoCreate: false
      secretKeys:
        bucket: S3_BUCKET
        accessKey: AWS_ACCESS_KEY_ID
        secretKey: AWS_SECRET_ACCESS_KEY
- op: replace
  path: /spec/values/replicaCount
  value: 0
- op: add
  path: /spec/values/affinity
  value:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: node-role.kubernetes.io/control-plane
                operator: DoesNotExist
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchLabels:
              app.kubernetes.io/component: app
              app.kubernetes.io/name: nextcloud
              app.kubernetes.io/instance: nextcloud
          topologyKey: kubernetes.io/hostname
- op: replace
  path: /spec/values/nextcloud/host
  value: cloud.myrobertson.com
- op: add
  path: /spec/values/nextcloud/extraEnv/-
  value:
    name: COLLABORA_PUBLIC_URL
    value: https://office.myrobertson.com
- op: add
  path: /spec/values/nextcloud/extraEnv/-
  value:
    name: COLLABORA_WOPI_URL
    value: http://nextcloud-collabora:9980
- op: add
  path: /spec/values/nextcloud/extraEnv/-
  value:
    name: NEXTCLOUD_OIDC_ENABLED
    value: "true"
- op: add
  path: /spec/values/nextcloud/extraEnv/-
  value:
    name: NEXTCLOUD_OIDC_PROVIDER_ID
    value: keycloak
- op: add
  path: /spec/values/nextcloud/extraEnv/-
  value:
    name: NEXTCLOUD_OIDC_CLIENT_ID
    valueFrom:
      secretKeyRef:
        name: nextcloud-oidc-secret
        key: OIDC_CLIENT_ID
- op: add
  path: /spec/values/nextcloud/extraEnv/-
  value:
    name: NEXTCLOUD_OIDC_CLIENT_SECRET
    valueFrom:
      secretKeyRef:
        name: nextcloud-oidc-secret
        key: OIDC_CLIENT_SECRET
- op: add
  path: /spec/values/nextcloud/extraEnv/-
  value:
    name: NEXTCLOUD_OIDC_DISCOVERY_URI
    value: https://sso.myrobertson.com/realms/homelab/.well-known/openid-configuration
- op: add
  path: /spec/values/nextcloud/extraEnv/-
  value:
    name: NEXTCLOUD_OIDC_ALLOW_MULTIPLE_USER_BACKENDS
    value: "1"
- op: add
  path: /spec/values/nextcloud/extraEnv/-
  value:
    name: NEXTCLOUD_OIDC_GROUP_PROVISIONING
    value: "0"
- op: add
  path: /spec/values/collabora
  value:
    enabled: false
    collabora:
      aliasgroups:
        - host: "https://cloud.myrobertson.com:443"
      extra_params: "--o:ssl.enable=false --o:ssl.termination=true"
      server_name: office.myrobertson.com
      existingSecret:
        enabled: true
        secretName: collabora-secret
    ingress:
      enabled: false
- op: replace
  path: /spec/values/redis/enabled
  value: false
- op: replace
  path: /spec/values/metrics/enabled
  value: false
- op: replace
  path: /spec/values/cronjob/enabled
  value: false
