apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: restic-config-n8n-cnpg-data
spec:
  type: kv-v2
  mount: secret
  path: volsync/prod/n8n-cnpg-1
  refreshAfter: 60s
  destination:
    create: true
    name: restic-config-n8n-cnpg-data
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: n8n-cnpg-data-backup
spec:
  sourcePVC: n8n-cnpg-1
  paused: false
  trigger:
    schedule: "16 * * * *"
  restic:
    repository: restic-config-n8n-cnpg-data
    pruneIntervalDays: 1
    retain:
      hourly: 4
      daily: 0
      weekly: 0
      monthly: 0
      yearly: 0
    copyMethod: Direct
    cacheStorageClassName: csi-cephfs-sc
    moverSecurityContext:
      runAsUser: 26
      runAsGroup: 26
      fsGroup: 26
    moverResources:
      requests:
        cpu: "500m"
        memory: "1Gi"
      limits:
        cpu: "2"
        memory: "4Gi"
