apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: n8n
spec:
  values:
    replicaCount: 1
    queueMode:
      enabled: true
      workerReplicaCount: 2
      workerConcurrency: 10
    webhook:
      url: https://n8n.myrobertson.com