apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: gotify-synology-migration
  namespace: default
spec:
  type: kv-v2
  mount: secret
  path: gotify/prod/migration
  refreshAfter: 60s
  destination:
    create: true
    name: gotify-synology-migration
