apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: nextcloud-ldap-secret
spec:
  type: kv-v2
  mount: secret
  path: nextcloud/env/ldap
  refreshAfter: 60s
  destination:
    create: true
    name: nextcloud-ldap-secret
