apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-data-pvc-ceph
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: ceph-filesystem-fuse
  volumeMode: Filesystem
