apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-data-pvc-ceph-v2
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: csi-cephfs-sc
  volumeMode: Filesystem
