apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: prometheus-operator-crds
  namespace: monitoring
spec:
  interval: 1h
  url: oci://ghcr.io/prometheus-community/charts/prometheus-operator-crds
  ref:
    semver: ">=23.x"
  layerSelector:
    mediaType: "application/vnd.cncf.helm.chart.content.v1.tar+gzip"
    operation: copy
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prometheus-operator-crds
  namespace: monitoring
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: prometheus-operator-crds
    namespace: monitoring
  install:
    crds: Create
  values: