apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: syncthing
spec:
  suspend: false
  values:
    workload:
      main:
        replicas: 1
    service:
      discovery:
        loadBalancerIP: 10.31.0.72
    persistence:
      downloads:
        enabled: true
