apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-dns
  namespace: external-dns
spec:
  values:
    txtOwnerId: staging.myrobertson.net
    domainFilters: [ .staging.myrobertson.net ]
