apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-dns
  namespace: external-dns
spec:
  values:
    provider:
      name: pdns
    extraArgs:
        - --source=service
        - --pdns-server=http://192.168.7.201:8001
        - --pdns-server-id=localhost
        - --pdns-api-key=$(PDNS_API_KEY) 
    txtOwnerId: staging.myrobertson.net
    domainFilters: [ staging.myrobertson.net ]
    extraVolumes: # to mount the PDNS API key secret
      - name: pdns-apikey
        secret:
          secretName: external-dns-pdns-apikey
    extraVolumeMounts:
      - name: pdns-apikey
        mountPath: /var/secrets/pdns
        readOnly: true
    env: # to set the PDNS API key from the mounted secret
      - name: PDNS_API_KEY
        valueFrom:
          secretKeyRef:
            name: external-dns-pdns-apikey
            key: pdns-api-key
