
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: rgw-admin-ops-user
  namespace: rook-ceph-external
spec:
  type: "kv-v2"
  mount: secret
  path: proxmox/cl0/ceph/rgw-admin-ops-user
  refreshAfter: 60s
  destination:
    create: true
    name: rgw-admin-ops-user
    type: kubernetes.io/rook
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: rook-ceph-mon
  namespace: rook-ceph-external
spec:
  type: "kv-v2"
  mount: secret
  path: proxmox/cl0/ceph/rook-ceph-mon
  refreshAfter: 60s
  destination:
    create: true
    name: rook-ceph-mon
    type: kubernetes.io/rook
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: rook-csi-rbd-node
  namespace: rook-ceph-external
spec:
  type: "kv-v2"
  mount: secret
  path: proxmox/cl0/ceph/rook-csi-rbd-node
  refreshAfter: 60s
  destination:
    create: true
    name: rook-csi-rbd-node
    type: kubernetes.io/rook
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: rook-csi-rbd-provisioner
  namespace: rook-ceph-external
spec:
  type: "kv-v2"
  mount: secret
  path: proxmox/cl0/ceph/rook-csi-rbd-provisioner
  refreshAfter: 60s
  destination:
    create: true
    name: rook-csi-rbd-provisioner
    type: kubernetes.io/rook
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: rook-csi-cephfs-node
  namespace: rook-ceph-external
spec:
  type: "kv-v2"
  mount: secret
  path: proxmox/cl0/ceph/rook-csi-cephfs-node
  refreshAfter: 60s
  destination:
    create: true
    name: rook-csi-cephfs-node
    type: kubernetes.io/rook
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: rook-csi-cephfs-provisioner
  namespace: rook-ceph-external
spec:
  type: "kv-v2"
  mount: secret
  path: proxmox/cl0/ceph/rook-csi-cephfs-provisioner
  refreshAfter: 60s
  destination:
    create: true
    name: rook-csi-cephfs-provisioner
    type: kubernetes.io/rook


    