apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: unifi-security-ssh
  namespace: monitoring
spec:
  type: kv-v2
  mount: secret
  path: unifi/ssh
  refreshAfter: 60s
  destination:
    create: true
    name: unifi-security-ssh
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: unifi-security-smtp
  namespace: monitoring
spec:
  type: kv-v2
  mount: secret
  path: mailu/prod/ses-relay
  refreshAfter: 60s
  destination:
    create: true
    name: unifi-security-smtp
