apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
  - ../../base/n8n
  - httpRoute.yaml
  - auth-policy.yaml
  - n8n-secret.yaml
patches:
  - path: n8n-values.yaml
    target:
      kind: HelmRelease
      name: n8n
  - patch: |
      $patch: delete
      apiVersion: secrets.hashicorp.com/v1beta1
      kind: VaultStaticSecret
      metadata:
        name: n8n-secret
    target:
      kind: VaultStaticSecret
      name: n8n-secret
  - patch: |
      - op: replace
        path: /spec/storage/size
        value: 5Gi
      - op: replace
        path: /spec/walStorage/size
        value: 2Gi
    target:
      kind: Cluster
      name: n8n-cnpg
