apiVersion: v1
kind: Secret
metadata:
  name: n8n-secret
type: Opaque
stringData:
  N8N_ENCRYPTION_KEY: staging-n8n-encryption-key
  N8N_HOST: n8n.staging.myrobertson.net
  N8N_PORT: "443"
  N8N_PROTOCOL: https
