apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radarr-config-ceph
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: csi-cephfs-sc
