apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radarr-config
spec:
  volumeName: pvc-762faa11-7615-4840-8133-cee1b136520c
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: synology-iscsi-storage
