---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: radarr
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: radarr
  values:
    persistence:
      config:
        enabled: true
        storageClass: synology-iscsi-storage
        targetSelector:
          main:
            main:
              mountPath: /config
            exportarr:
              mountPath: /config
              readOnly: true
