apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: radarr
spec:
  interval: 1h
  url: oci://oci.trueforge.org/truecharts/radarr
  ref:
    tag: "27.2.1"
  layerSelector:
    mediaType: "application/vnd.cncf.helm.chart.content.v1.tar+gzip"
    operation: copy
