---
apiVersion: ceph.rook.io/v1
kind: CephObjectStore
metadata:
  name: external-store
  namespace: rook-ceph
spec:
  gateway:
    port: 7480
    externalRgwEndpoints:
      - ip: 192.168.10.3 


# kubectl -n rook-ceph-external create secret generic 
# --type="" rgw-admin-ops-user 
# --from-literal=accessKey=3H65EE4UAVMOCM2KQMVM 
# --from-literal=secretKey=ubJ3t7Zfbv3yTMeDTSuTsIs3TkDjCBEqUcHh92Gc


