
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: issuer
  namespace: cert-manager
---
apiVersion: v1
kind: Secret
metadata:
  name: issuer-token-lmzpj
  namespace: cert-manager
  annotations:
    kubernetes.io/service-account.name: issuer
type: kubernetes.io/service-account-token
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cert-manager-vault-token-creator
  namespace: cert-manager # Or the namespace where your Vault Issuer/ClusterIssuer is
rules:
- apiGroups: [""]
  resources: ["serviceaccounts/token"]
  resourceNames: ["issuer"] # The name of the service account cert-manager needs to get a token for
  verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cert-manager-vault-token-creator
  namespace: cert-manager
subjects:
  - kind: ServiceAccount
    name: cert-manager
    namespace: cert-manager
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cert-manager-vault-token-creator
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: vault-issuer
  namespace: cert-manager
spec:
  vault:
    server: https://vault.myrobertson.net:8200
    path: pki_int/sign/myrobertson-dot-net
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURkRENDQWx5Z0F3SUJBZ0lVVlBFUjMxdDl1REdRZXhhV2JHeUNybUphK3Njd0RRWUpLb1pJaHZjTkFRRUwKQlFBd01URXZNQzBHQTFVRUF4TW1iWGx5YjJKbGNuUnpiMjR1Ym1WMElFbHVkR1Z5YldWa2FXRjBaU0JCZFhSbwpiM0pwZEhrd0hoY05NalV4TURBM01ERXlNakl5V2hjTk1qVXhNVEEyTURFeU1qVXlXakFnTVI0d0hBWURWUVFECkV4VjJZWFZzZEM1dGVYSnZZbVZ5ZEhOdmJpNXVaWFF3Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXcKZ2dFS0FvSUJBUUNtWjBXN2FZMStJWjQ3eTkyZkhNampnbjBrd3FWd0h2RGVWU0NKNWVZNHRlejYwSXhlRDlBUgpndkJ4NWUxalBCcXdrdEVHcTRYY0dJTkJ6NzQ1bm1KcHRsTFdWRWJPcWJjeEJ4SzVHK3hMeC9RRVpXWkZKbnh1CmVKZk5nV090WUNUdWdwTXIrKzBQbVFVSjQ0VTdsWURudTEyTDlTUjFEaVVsL2FDdno5VjJmdW90UGc2dTc3Nm4KYkltTXZSSWxYTTZFZ1Ixa01RampRMlVoalRlVzhqYVNuZHUxbGNza25kTkEwR254NG9RWkFkNmRVYlZrdEpabgpyMzgzenZzcWx0T2JvS3NyeVAyUEZ3NEkvSWlrOXZub0lTMnBFRlFMQk5RVk92L01RYUhpK210NXYzM0czS0NDCjZ4TVJwQXVQT0dFSi9kU3V2bU5laTlIZG5YZXVvUkNQQWdNQkFBR2pnWlF3Z1pFd0RnWURWUjBQQVFIL0JBUUQKQWdPb01CMEdBMVVkSlFRV01CUUdDQ3NHQVFVRkJ3TUJCZ2dyQmdFRkJRY0RBakFkQmdOVkhRNEVGZ1FVTHg0UgpaQ0hJbmNnZEYxL1pZMHE1dmhrcGp5QXdId1lEVlIwakJCZ3dGb0FVRnFjMXZ6R0dVOVhtcGRRdFcweWNDOXVrCkNDSXdJQVlEVlIwUkJCa3dGNElWZG1GMWJIUXViWGx5YjJKbGNuUnpiMjR1Ym1WME1BMEdDU3FHU0liM0RRRUIKQ3dVQUE0SUJBUUF1ekhTdWF4SmNSRFRkcFRCbHY1YkRMd2VtdmlnNWZyRWJxazBGM2VvekxnSzFMYTZyMXZiMwozZmRIQ1ByWmhGK0wzeTFQUERzMW1pZFpiNmpXRWtoVko1dHNJSTZUVU55cHhEdUwrNG0rQ25INGpBbWFDSkZkClFkemtRZHRDNWF2Z0tiMTlwc1NBeE1LaDVEU0JaL3FzQVBRenkxQTRxMjRzYnRZUXdKUTVCNDFtOEVnaEVDTksKZjg2MDZTb0dqbnUycGpwQWJybDZTUWhSVk5tOFN2YkJiNE1UMFNna0E3Uk4yb1ZaanExTnppd21qd05VSDNzTwpxbS9KR1Bua1NnOGdaeEJIc3d5bTAyelU1ZWNYWmU2N1FsdllnVnAxb2QrTmlRZEpLc1Bxem5rUWhRa3JzZjcyCll6dlVUNHU2cWRYWlpwRSttNkVqRVk0VWNPU1IvdVVNCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0=
    auth:
      kubernetes:
        mountPath: /v1/auth/staging-kubernetes
        role: vault-cert-issuer-role
        serviceAccountRef:
          name: default
          audiences: 
            - "https://cp.staging.myrobertson.net:6443"
        # secretRef:
        #   name: issuer-token-lmzpj
        #   key: token
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: vault-issuer
  namespace: cert-manager
spec:
  vault:
    server: https://vault.myrobertson.net:8200
    path: pki_int/sign/myrobertson-dot-net
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURkRENDQWx5Z0F3SUJBZ0lVVlBFUjMxdDl1REdRZXhhV2JHeUNybUphK3Njd0RRWUpLb1pJaHZjTkFRRUwKQlFBd01URXZNQzBHQTFVRUF4TW1iWGx5YjJKbGNuUnpiMjR1Ym1WMElFbHVkR1Z5YldWa2FXRjBaU0JCZFhSbwpiM0pwZEhrd0hoY05NalV4TURBM01ERXlNakl5V2hjTk1qVXhNVEEyTURFeU1qVXlXakFnTVI0d0hBWURWUVFECkV4VjJZWFZzZEM1dGVYSnZZbVZ5ZEhOdmJpNXVaWFF3Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXcKZ2dFS0FvSUJBUUNtWjBXN2FZMStJWjQ3eTkyZkhNampnbjBrd3FWd0h2RGVWU0NKNWVZNHRlejYwSXhlRDlBUgpndkJ4NWUxalBCcXdrdEVHcTRYY0dJTkJ6NzQ1bm1KcHRsTFdWRWJPcWJjeEJ4SzVHK3hMeC9RRVpXWkZKbnh1CmVKZk5nV090WUNUdWdwTXIrKzBQbVFVSjQ0VTdsWURudTEyTDlTUjFEaVVsL2FDdno5VjJmdW90UGc2dTc3Nm4KYkltTXZSSWxYTTZFZ1Ixa01RampRMlVoalRlVzhqYVNuZHUxbGNza25kTkEwR254NG9RWkFkNmRVYlZrdEpabgpyMzgzenZzcWx0T2JvS3NyeVAyUEZ3NEkvSWlrOXZub0lTMnBFRlFMQk5RVk92L01RYUhpK210NXYzM0czS0NDCjZ4TVJwQXVQT0dFSi9kU3V2bU5laTlIZG5YZXVvUkNQQWdNQkFBR2pnWlF3Z1pFd0RnWURWUjBQQVFIL0JBUUQKQWdPb01CMEdBMVVkSlFRV01CUUdDQ3NHQVFVRkJ3TUJCZ2dyQmdFRkJRY0RBakFkQmdOVkhRNEVGZ1FVTHg0UgpaQ0hJbmNnZEYxL1pZMHE1dmhrcGp5QXdId1lEVlIwakJCZ3dGb0FVRnFjMXZ6R0dVOVhtcGRRdFcweWNDOXVrCkNDSXdJQVlEVlIwUkJCa3dGNElWZG1GMWJIUXViWGx5YjJKbGNuUnpiMjR1Ym1WME1BMEdDU3FHU0liM0RRRUIKQ3dVQUE0SUJBUUF1ekhTdWF4SmNSRFRkcFRCbHY1YkRMd2VtdmlnNWZyRWJxazBGM2VvekxnSzFMYTZyMXZiMwozZmRIQ1ByWmhGK0wzeTFQUERzMW1pZFpiNmpXRWtoVko1dHNJSTZUVU55cHhEdUwrNG0rQ25INGpBbWFDSkZkClFkemtRZHRDNWF2Z0tiMTlwc1NBeE1LaDVEU0JaL3FzQVBRenkxQTRxMjRzYnRZUXdKUTVCNDFtOEVnaEVDTksKZjg2MDZTb0dqbnUycGpwQWJybDZTUWhSVk5tOFN2YkJiNE1UMFNna0E3Uk4yb1ZaanExTnppd21qd05VSDNzTwpxbS9KR1Bua1NnOGdaeEJIc3d5bTAyelU1ZWNYWmU2N1FsdllnVnAxb2QrTmlRZEpLc1Bxem5rUWhRa3JzZjcyCll6dlVUNHU2cWRYWlpwRSttNkVqRVk0VWNPU1IvdVVNCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0=
    auth:
      kubernetes:
        mountPath: /v1/auth/staging-kubernetes
        role: vault-cert-issuer-role
        serviceAccountRef:
          name: issuer
          audiences: 
            - "https://cp.staging.myrobertson.net:6443"