

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cert-manager-vault-token-creator
  namespace: cert-manager # Or the namespace where your Vault Issuer/ClusterIssuer is
rules:
- apiGroups: [""]
  resources: ["serviceaccounts/token"]
  resourceNames: ["default"] # The name of the service account cert-manager needs to get a token for
  verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cert-manager-vault-token-creator
  namespace: cert-manager
subjects:
  - kind: ServiceAccount
    name: default
    namespace: cert-manager 
  - kind: ServiceAccount
    name: cert-manager
    namespace: cert-manager
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cert-manager-vault-token-creator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cert-manager-tokenreview
subjects:
  - kind: ServiceAccount
    name: default
    namespace: cert-manager 
  - kind: ServiceAccount
    name: cert-manager
    namespace: cert-manager 
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: vault-issuer
  namespace: cert-manager
spec:
  vault:
    server: https://vault.myrobertson.net:8200
    path: pki_int_dev/sign/cluster_ssl_certs
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUR5ekNDQTNHZ0F3SUJBZ0lUSWdBQUFBZEVZRTNXcXRqeUtRQUFBQUFBQnpBS0JnZ3Foa2pPUFFRREFqQlIKTVJNd0VRWUtDWkltaVpQeUxHUUJHUllEYm1WME1Sc3dHUVlLQ1pJbWlaUHlMR1FCR1JZTGJYbHliMkpsY25SegpiMjR4SFRBYkJnTlZCQU1URkcxNWNtOWlaWEowYzI5dUxVUkRNUzFEUVMweE1CNFhEVEkxTVRBeU1ERTVNVEV5Ck9Wb1hEVE0zTVRBeE56RTVNVEV5T1Zvd01ERXVNQ3dHQTFVRUF4TWxWbUYxYkhRZ1RYbFNiMkpsY25SemIyNHUKYm1WMElFbHVkR1Z5YldWa2FXRjBaU0JEUVRCWk1CTUdCeXFHU000OUFnRUdDQ3FHU000OUF3RUhBMElBQktCRQp0MEVYbUZqVUIrYTY4OCtjTGRydzdBTmFVWFhWRlF0alNXOXRZNVlCUmxYWUN3OG9MaFVVeHZtcUUxeCtoNkE5CkIxMWpEQ05pUHR5bjNrMVRrNzZqZ2dKSE1JSUNRekFkQmdOVkhRNEVGZ1FVcnJ0d2M2QUpBOVI1ODhVMncrYXEKd0RTTGZuRXdId1lEVlIwakJCZ3dGb0FVUTNncG9iWmNvZUVjZ2thVGJGc0poNFVrQ0lrd2dkSUdBMVVkSHdTQgp5akNCeHpDQnhLQ0J3YUNCdm9hQnUyeGtZWEE2THk4dlEwNDliWGx5YjJKbGNuUnpiMjR0UkVNeExVTkJMVEVzClEwNDlaR014TEVOT1BVTkVVQ3hEVGoxUWRXSnNhV01sTWpCTFpYa2xNakJUWlhKMmFXTmxjeXhEVGoxVFpYSjIKYVdObGN5eERUajFEYjI1bWFXZDFjbUYwYVc5dUxFUkRQVzE1Y205aVpYSjBjMjl1TEVSRFBXNWxkRDlqWlhKMAphV1pwWTJGMFpWSmxkbTlqWVhScGIyNU1hWE4wUDJKaGMyVS9iMkpxWldOMFEyeGhjM005WTFKTVJHbHpkSEpwClluVjBhVzl1VUc5cGJuUXdnY29HQ0NzR0FRVUZCd0VCQklHOU1JRzZNSUczQmdnckJnRUZCUWN3QW9hQnFteGsKWVhBNkx5OHZRMDQ5YlhseWIySmxjblJ6YjI0dFJFTXhMVU5CTFRFc1EwNDlRVWxCTEVOT1BWQjFZbXhwWXlVeQpNRXRsZVNVeU1GTmxjblpwWTJWekxFTk9QVk5sY25acFkyVnpMRU5PUFVOdmJtWnBaM1Z5WVhScGIyNHNSRU05CmJYbHliMkpsY25SemIyNHNSRU05Ym1WMFAyTkJRMlZ5ZEdsbWFXTmhkR1UvWW1GelpUOXZZbXBsWTNSRGJHRnoKY3oxalpYSjBhV1pwWTJGMGFXOXVRWFYwYUc5eWFYUjVNQThHQTFVZEV3RUIvd1FGTUFNQkFmOHdEZ1lEVlIwUApBUUgvQkFRREFnR0dNRDRHQ1NzR0FRUUJnamNWQndReE1DOEdKeXNHQVFRQmdqY1ZDSWVxclhTSG1LRVFnWVdaCktJUHR0M2FGbDc4Y2dXR0hqZW8yZ2FYb1NnSUJaQUlCQXpBS0JnZ3Foa2pPUFFRREFnTklBREJGQWlBUU1IYTAKTFUzaWdaZ1hhM3djYTY0TGY3MlJ5VWdIbXFCZTlqZDdLYjUwRndJaEFQN3crdVhERnlVSkdteXMyY2hSRksrNgp0UVJmRFFxbFRjdjZnSkNxR2RWSAotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    auth:
      kubernetes:
        mountPath: /v1/auth/dev-kubernetes
        role: vault-cert-issuer-role
        serviceAccountRef:
          name: default
          audiences: 
            - "https://cp.dev.myrobertson.net:6443"
        # secretRef:
        #   name: issuer-token-lmzpj
        #   key: token
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: vault-issuer
  namespace: cert-manager
spec:
  vault:
    server: https://vault.myrobertson.net:8200
    path: pki_int_dev/sign/cluster_ssl_certs
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUR5ekNDQTNHZ0F3SUJBZ0lUSWdBQUFBZEVZRTNXcXRqeUtRQUFBQUFBQnpBS0JnZ3Foa2pPUFFRREFqQlIKTVJNd0VRWUtDWkltaVpQeUxHUUJHUllEYm1WME1Sc3dHUVlLQ1pJbWlaUHlMR1FCR1JZTGJYbHliMkpsY25SegpiMjR4SFRBYkJnTlZCQU1URkcxNWNtOWlaWEowYzI5dUxVUkRNUzFEUVMweE1CNFhEVEkxTVRBeU1ERTVNVEV5Ck9Wb1hEVE0zTVRBeE56RTVNVEV5T1Zvd01ERXVNQ3dHQTFVRUF4TWxWbUYxYkhRZ1RYbFNiMkpsY25SemIyNHUKYm1WMElFbHVkR1Z5YldWa2FXRjBaU0JEUVRCWk1CTUdCeXFHU000OUFnRUdDQ3FHU000OUF3RUhBMElBQktCRQp0MEVYbUZqVUIrYTY4OCtjTGRydzdBTmFVWFhWRlF0alNXOXRZNVlCUmxYWUN3OG9MaFVVeHZtcUUxeCtoNkE5CkIxMWpEQ05pUHR5bjNrMVRrNzZqZ2dKSE1JSUNRekFkQmdOVkhRNEVGZ1FVcnJ0d2M2QUpBOVI1ODhVMncrYXEKd0RTTGZuRXdId1lEVlIwakJCZ3dGb0FVUTNncG9iWmNvZUVjZ2thVGJGc0poNFVrQ0lrd2dkSUdBMVVkSHdTQgp5akNCeHpDQnhLQ0J3YUNCdm9hQnUyeGtZWEE2THk4dlEwNDliWGx5YjJKbGNuUnpiMjR0UkVNeExVTkJMVEVzClEwNDlaR014TEVOT1BVTkVVQ3hEVGoxUWRXSnNhV01sTWpCTFpYa2xNakJUWlhKMmFXTmxjeXhEVGoxVFpYSjIKYVdObGN5eERUajFEYjI1bWFXZDFjbUYwYVc5dUxFUkRQVzE1Y205aVpYSjBjMjl1TEVSRFBXNWxkRDlqWlhKMAphV1pwWTJGMFpWSmxkbTlqWVhScGIyNU1hWE4wUDJKaGMyVS9iMkpxWldOMFEyeGhjM005WTFKTVJHbHpkSEpwClluVjBhVzl1VUc5cGJuUXdnY29HQ0NzR0FRVUZCd0VCQklHOU1JRzZNSUczQmdnckJnRUZCUWN3QW9hQnFteGsKWVhBNkx5OHZRMDQ5YlhseWIySmxjblJ6YjI0dFJFTXhMVU5CTFRFc1EwNDlRVWxCTEVOT1BWQjFZbXhwWXlVeQpNRXRsZVNVeU1GTmxjblpwWTJWekxFTk9QVk5sY25acFkyVnpMRU5PUFVOdmJtWnBaM1Z5WVhScGIyNHNSRU05CmJYbHliMkpsY25SemIyNHNSRU05Ym1WMFAyTkJRMlZ5ZEdsbWFXTmhkR1UvWW1GelpUOXZZbXBsWTNSRGJHRnoKY3oxalpYSjBhV1pwWTJGMGFXOXVRWFYwYUc5eWFYUjVNQThHQTFVZEV3RUIvd1FGTUFNQkFmOHdEZ1lEVlIwUApBUUgvQkFRREFnR0dNRDRHQ1NzR0FRUUJnamNWQndReE1DOEdKeXNHQVFRQmdqY1ZDSWVxclhTSG1LRVFnWVdaCktJUHR0M2FGbDc4Y2dXR0hqZW8yZ2FYb1NnSUJaQUlCQXpBS0JnZ3Foa2pPUFFRREFnTklBREJGQWlBUU1IYTAKTFUzaWdaZ1hhM3djYTY0TGY3MlJ5VWdIbXFCZTlqZDdLYjUwRndJaEFQN3crdVhERnlVSkdteXMyY2hSRksrNgp0UVJmRFFxbFRjdjZnSkNxR2RWSAotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    auth:
      kubernetes:
        mountPath: /v1/auth/dev-kubernetes
        role: vault-cert-issuer-role
        serviceAccountRef:
          name: default
          audiences: 
            - "https://cp.dev.myrobertson.net:6443"