apiVersion: secrets.hashicorp.com/v1beta1
kind: SecretTransformation
metadata:
  name: cnpg-backblaze-b2
spec:
  excludes:
    - .*
  templates:
    AWS_ACCESS_KEY_ID:
      text: '{{- template "awsAccessKeyId" . -}}'
    AWS_SECRET_ACCESS_KEY:
      text: '{{- template "awsSecretAccessKey" . -}}'
  sourceTemplates:
    - name: helpers
      text: |
        {{- define "awsAccessKeyId" -}}
        {{- coalesce
              (get .Secrets "AWS_ACCESS_KEY_ID")
              (get .Secrets "applicationKeyId")
              (get .Secrets "APPLICATION_KEY_ID")
              (get .Secrets "BACKBLAZE_APPLICATION_KEY_ID")
              (get .Secrets "B2_APPLICATION_KEY_ID")
              (get .Secrets "keyID")
              (get .Secrets "keyId")
        -}}
        {{- end -}}

        {{- define "awsSecretAccessKey" -}}
        {{- coalesce
              (get .Secrets "AWS_SECRET_ACCESS_KEY")
              (get .Secrets "applicationKey")
              (get .Secrets "APPLICATION_KEY")
              (get .Secrets "BACKBLAZE_APPLICATION_KEY")
              (get .Secrets "B2_APPLICATION_KEY")
        -}}
        {{- end -}}
