apiVersion: batch/v1
kind: Job
metadata:
  name: import-external-ceph-cluster
  namespace: rook-ceph-external
spec:
  template:
    spec:
      containers:
      - name: kubectl-python-runner
        image: bitnami/kubectl
        command: ["/bin/bash", "/app/script.sh"]
        volumeMounts:
          - name: secret-volume
            readOnly: true
            mountPath: "/app"
      volumes:
      - name: secret-volume
        secret:
          secretName: import-external-cluster-script
      restartPolicy: OnFailure
