apiVersion: batch/v1
kind: Job
metadata:
  name: import-external-cluster
  namespace: rook-ceph-external
spec:
  template:
    spec:
      containers:
      - name: python-runner
        image: python:3.9  # Or your custom image with the script
        command: ["/bin/bash", "/app/script.sh"]
        volumeMounts:
          - name: secret-volume
            readOnly: true
            mountPath: "/app"
      volumes:
      - name: secret-volume
        secret:
          secretName: import-external-cluster-script
      restartPolicy: OnFailure
  backoffLimit: 4