apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: istio-federation
  namespace: monitoring
  labels:
    app.kubernetes.io/name: istio-prometheus
spec:
  namespaceSelector:
    matchNames:
    - istio-system
  selector:
    matchLabels:
      app.kubernetes.io/name: prometheus
  endpoints:
  - interval: 30s
    scrapeTimeout: 25s
    params:
      'match[]':
      - '{__name__="istio_requests_total"}'
      - '{__name__="istio_request_duration_milliseconds_bucket"}'
      - '{__name__="istio_request_bytes_bucket"}'
      - '{__name__="istio_request_bytes_sum"}'
      - '{__name__="istio_response_bytes_bucket"}'
      - '{__name__="istio_response_bytes_sum"}'
      - '{__name__=~"pilot(.*)"}'
    path: /federate
    targetPort: 9090
    honorLabels: true