apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cluster-issuers.yaml
  - ceph-object-store.yaml
  - rook-external-cluster.yaml
  - synology-csi.yaml
spec:
  wait: true
    
