apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cluster-issuers.yaml
  - rook-external-cluster.yaml
  - gotify-bridge.yml
  - bgp-config.yaml
  - flux-alertmanager.yaml
  - podmonitor.yaml
  - monitoring-prometheus-gateway.yaml
  - monitoring-alertmanager-gateway.yaml
  - monitoring-grafana-gateway.yaml
  - toolbox.yaml
  - istio-servicemonitor.yaml
  - istio-gateway-alerts.yaml
spec:
  wait: true
configMapGenerator:
  - name: flux-grafana-dashboards
    namespace: monitoring
    files:
      - dashboards/control-plane.json
      - dashboards/cluster.json
      - dashboards/logs.json
    options:
      labels:
        grafana_dashboard: "1"
        app.kubernetes.io/part-of: flux
        app.kubernetes.io/component: monitoring
        kustomize.toolkit.fluxcd.io/substitute: disabled
  - name: istio-grafana-dashboards
    namespace: monitoring
    files:
      - dashboards/istio-mesh-dashboard.json
      - dashboards/istio-service-dashboard.json
      - dashboards/istio-workload-dashboard.json
      - dashboards/istio-pilot-dashboard.json
      - dashboards/istio-ztunnel-dashboard.json
      - dashboards/istio-performance-dashboard.json
      - dashboards/istio-gateway-case-metrics.json
      - dashboards/istio-gateway-service-drilldown.json
    options:
      labels:
        grafana_dashboard: "1"
        app.kubernetes.io/part-of: istio
        app.kubernetes.io/component: monitoring
        kustomize.toolkit.fluxcd.io/substitute: disabled

