apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cluster-issuers.yaml
  - rook-external-cluster.yaml
  - gotify-bridge.yml
  - ipaddresspool.yaml
  - flux-alertmanager.yaml
  - podmonitor.yaml
  - monitoring-gateway.yaml
  - prometheus-gateway.yaml
  - alertmanager-gateway.yaml
spec:
  wait: true
configMapGenerator:
  - name: flux-grafana-dashboards
    namespace: monitoring
    files:
      - dashboards/control-plane.json
      - dashboards/cluster.json
      - dashboards/logs.json
    options:
      labels:
        grafana_dashboard: "1"
        app.kubernetes.io/part-of: flux
        app.kubernetes.io/component: monitoring
        kustomize.toolkit.fluxcd.io/substitute: disabled
    
