apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: flux-system
  namespace: monitoring
  labels:
    app.kubernetes.io/part-of: flux
    app.kubernetes.io/component: monitoring
spec:
  namespaceSelector:
    matchNames:
      - flux-system
  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - helm-controller
          - source-controller
          - kustomize-controller
          - notification-controller
          - image-automation-controller
          - image-reflector-controller
  podMetricsEndpoints:
    - port: http-prom
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: syncthing
  namespace: monitoring
  labels:
    app.kubernetes.io/part-of: syncthing
    app.kubernetes.io/component: monitoring
spec:
  namespaceSelector:
    matchNames:
      - default
  selector:
    matchLabels:
      app.kubernetes.io/name: syncthing
  podMetricsEndpoints:
    - port: http
      path: /metrics
      interval: 30s
      authorization:
        type: Bearer
        credentials:
          name: syncthing-metrics-token
          key: token