apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: mailu-wireguard-home-peer
spec:
  type: kv-v2
  mount: secret
  path: mailu/prod/wireguard-home-peer
  refreshAfter: 60s
  destination:
    create: true
    name: mailu-wireguard-home-peer
