apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: external-dns
resources:
  - imagepullsecrets.yaml
  - namespace.yaml
  - pdns-apikey.yaml
  - repository.yaml
  - release.yaml
