apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-dns
  namespace: external-dns
spec:
  interval: 30m
  chart:
    spec:
      chart: './charts/external-dns'
      sourceRef:
        kind: GitRepository
        name: external-dns
        namespace: external-dns
      interval: 10m
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  
  values:
    # global:
    #   imagePullSecrets:
    #     - name: imagepullsecrets
    sources: 
      - gateway-httproute
    provider:
      name: pdns
    extraArgs:
        - --source=service # or ingress or both
        - --pdns-server=http://192.168.7.201:8001
        - --pdns-server-id=subns
        - --pdns-api-key=$(PDNS_API_KEY) 
    logLevel: debug
    logFormat: json
    extraVolumes: # to mount the PDNS API key secret
      - name: pdns-apikey
        secret:
          secretName: external-dns-pdns-apikey
    extraVolumeMounts:
      - name: pdns-apikey
        mountPath: /var/secrets/pdns
        readOnly: true
    env: # to set the PDNS API key from the mounted secret
      - name: PDNS_API_KEY
        valueFrom:
          secretKeyRef:
            name: external-dns-pdns-apikey
            key: pdns-api-key
    rbac:  # @schema additionalProperties: true
      # -- If `true`, create a `ClusterRole` & `ClusterRoleBinding` with access to the Kubernetes API.
      create: true
      # -- Additional rules to add to the `ClusterRole`.
      additionalPermissions:
        - apiGroups: [""]
          resources: ["services", "pods", "nodes", "endpoints", "namesaces"]
          verbs: ["get", "watch", "list"]
        - apiGroups: ["networking.k8s.io"]
          resources: ["ingresses", "ingressclasses", "httproutes"]
          verbs: ["get", "watch", "list"]
        - apiGroups: ["gateway.networking.k8s.io"]
          resources: ["gateways", "httproutes"]
          verbs: ["get", "watch", "list"]
        - apiGroups: ["discovery.k8s.io"]
          resources: ["endpointslices"]
          verbs: ["get", "watch", "list"]

    serviceMonitor:
      enabled: true