---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: external-dns
  namespace: external-dns
spec:
  interval: 120m0s
  url: https://github.com/kubernetes-sigs/external-dns/
  ref:
    branch: master