apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: external-dns
  namespace: external-dns
spec:
  interval: 1h
  url: oci://registry-1.docker.io/bitnamicharts/external-dns
  layerSelector:
    mediaType: "application/vnd.cncf.helm.chart.content.v1.tar+gzip"
    operation: copy
  ref:
    semver: ">= 9.0.x"