apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
  - ../../base/jellyfin
patches:
  - path: jellyfin-values.yaml
    target:
      kind: HelmRelease
  - patch: |
      - op: replace
        path: /metadata/annotations/cert-manager.io~1common-name
        value: jellyfin.staging.myrobertson.net
      - op: replace
        path: /spec/listeners/0/hostname
        value: jellyfin.staging.myrobertson.net
      - op: replace
        path: /spec/infrastructure/annotations/external-dns.alpha.kubernetes.io~1hostname
        value: jellyfin.staging.myrobertson.net
    target:
      kind: Gateway
      name: jellyfin
  - patch: |
      - op: replace
        path: /spec/hostnames/0
        value: jellyfin.staging.myrobertson.net
    target:
      kind: HTTPRoute
      name: jellyfin