apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: readarr
spec:
  values:

    readarr:
      api:
        general:
          baseUrl: https://readarr.myrobertson.com
    workload:
      main:
        replicas: 1
    persistence:
      media:
        enabled: true
