apiVersion: apps/v1
kind: Deployment
metadata:
  name: pdns-admin
  namespace: powerdns
  labels:
    app: pdns-admin
    release: pdns-admin
spec:
  strategy:
    type: RollingUpdate
  replicas: 1
  selector:
    matchLabels:
      app: pdns-admin
      release: pdns-admin
  template:
    metadata:
      labels:
        app: pdns-admin
        release: pdns-admin
    spec:
      volumes:
        # - name: config
        #   configMap:
        #     name: pdns-recursor
        #     items:
        #       - key: recursor.conf
        #         path: recursor.conf
        # - name: zones
        #   configMap:
        #     name: pdns-recursor
        #     items:
        #       # {{- range .Values.pdns.recursor.zones }}
        #       # - key: {{ .name }}.conf
        #       #   path: {{ .name }}.conf
        #       # - key: {{ .name }}.zone
        #       #   path: {{ .name }}.zone
        #       # {{- end}}
        - name: api-data
          # {{- if .Values.pdns.recursor.persistence.enabled }}
          # persistentVolumeClaim:
          #   claimName: {{ template "fullname" . }}
          # {{- else }}
          emptyDir: {}
      containers:
        - name: pdns-admin
          image: "powerdnsadmin/pda-legacy:latest"
          imagePullPolicy: IfNotPresent
          # command: ["entrypoint.sh"]
          # args: ["SECRET_KEY='PowerDNSAPI'"]
          # env:
          #   - name: PDNS_API_KEY
          #     valueFrom:
          #       secretKeyRef:
          #         name: {{ template "fullname" . }}
          #         key: api-key
          ports:
            - name: api
              containerPort: 80
              protocol: TCP
          envFrom:
            - configMapRef:
                name: powerdnsadmin-env
          volumeMounts:
          # - name: config
          #   mountPath: /etc/pdns
          # - name: zones
          #   mountPath: /zones
          - name: api-data
            mountPath: /data
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: api
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: api
          resources: {}
      nodeSelector: {}
      affinity: {}
      tolerations: []