apiVersion: v1
kind: Service
metadata:
  name: pdns-auth
  namespace: powerdns
  labels:
    app: pdns-auth
    release: pdns-auth
spec:
  type: LoadBalancer
  ports:
    - port: 8081
      targetPort: 8081
      protocol: TCP
      name: api
    - port: 53
      targetPort: 53
      protocol: UDP
      name: dns-udp
    - port: 53
      targetPort: 53
      protocol: TCP
      name: dns-tcp
  selector:
    app: pdns-auth
    release: pdns-auth