apiVersion: apps/v1
kind: Deployment
metadata:
  name: pdns-recursor
  namespace: powerdns
  labels:
    app: pdns-recursor
    release: pdns-recursor
spec:
  replicas: 1
  selector:
    matchLabels:
    app: pdns-recursor
    release: pdns-recursor
  template:
    metadata:
      labels:
        app: pdns-recursor
        release: pdns-recursor
    spec:
      volumes:
        - name: config
          configMap:
            name: pdns-recursor
            items:
              - key: recursor.conf
                path: recursor.conf
        - name: zones
          configMap:
            name: pdns-recursor
            items:
              # {{- range .Values.pdns.recursor.zones }}
              # - key: {{ .name }}.conf
              #   path: {{ .name }}.conf
              # - key: {{ .name }}.zone
              #   path: {{ .name }}.zone
              # {{- end}}
        - name: api-data
          # {{- if .Values.pdns.recursor.persistence.enabled }}
          # persistentVolumeClaim:
          #   claimName: {{ template "fullname" . }}
          # {{- else }}
          emptyDir: {}
      containers:
        - name: pdns-recursor
          image: "powerdns/pdns-recursor-49:latest"
          imagePullPolicy: IfNotPresent
          command: ["/usr/local/sbin/pdns_recursor-startup"]
          args: ["--api-key=PowerDNSAPI", "--webserver-allow-from=0.0.0.0/0"]
          # env:
          #   - name: PDNS_API_KEY
          #     valueFrom:
          #       secretKeyRef:
          #         name: {{ template "fullname" . }}
          #         key: api-key
          ports:
            - name: dns-udp
              containerPort: 53
              protocol: UDP
            - name: dns-tcp
              containerPort: 53
              protocol: TCP
            - name: api
              containerPort: 8081
              protocol: TCP
          volumeMounts:
          - name: config
            mountPath: /etc/pdns
          - name: zones
            mountPath: /zones
          - name: api-data
            mountPath: /data
          livenessProbe:
            httpGet:
              path: /
              port: api
          readinessProbe:
            httpGet:
              path: /
              port: api
          resources: {}
      nodeSelector: {}
      affinity: {}
      tolerations: []