apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - authelia
  - readarr
  - external-dns
  - immich
  - lidarr
  - loki-stack
  - mealie
  - overseerr
  - plex
  - prowlarr
  - radarr
  - sonarr
  - syncthing
