apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - authelia
  - code-server
  - external-dns
  - immich
  - lidarr
  - loki-stack
  - mealie
  - n8n
  - overseerr
  - plex
  - prowlarr
  - radarr
  - redis-operator
  - sonarr
  - syncthing
  - task-control-plane
  - trilium
