apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: mailu-config
spec:
  type: kv-v2
  mount: secret
  path: mailu/env/config
  refreshAfter: 60s
  destination:
    create: true
    name: mailu-config
