apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: readarr
spec:
  interval: 1h
  url: oci://oci.trueforge.org/truecharts/readarr
  ref:
    semver: ">=22.x"
  layerSelector:
    mediaType: "application/vnd.cncf.helm.chart.content.v1.tar+gzip"
    operation: copy
