apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mealie
spec:
  values:

    # service:
    #   main:
    #     ports:
    #       main:
    #         port: 10018
    #         protocol: http
    mealie:
      api:
        general:
          baseUrl: https://mealie.staging.myrobertson.net
    server:
      controllers:
        main:
          replicas: 1
    workload:
      main:
        podSpec:
          containers:
            main:
              env: 
                API_PORT: "10018"
                LOG_LEVEL: debug
                DB_ENGINE: postgres
                POSTGRES_SERVER:
                  valueFrom:
                    secretKeyRef:
                      name: mealie-cnpg-main-app
                      key: host
                POSTGRES_PORT:
                  valueFrom:
                    secretKeyRef:
                      name: mealie-cnpg-main-app
                      key: port
                POSTGRES_DB:
                  valueFrom:
                    secretKeyRef:
                      name: mealie-cnpg-main-app
                      key: dbname
                POSTGRES_USER:
                  valueFrom:
                    secretKeyRef:
                      name: mealie-cnpg-main-app
                      key: username
                POSTGRES_PASSWORD:
                  valueFrom:
                    secretKeyRef:
                      name: mealie-cnpg-main-app
                      key: password
              envFrom:
                - secretRef:
                    name: mealie-oidc
                    expandObjectName: false
   