apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mealie
spec:
  values:

    # service:
    #   main:
    #     ports:
    #       main:
    #         port: 10018
    #         protocol: http
    mealie:
      api:
        general:
          baseUrl: https://mealie.staging.myrobertson.net
    server:
      controllers:
        main:
          replicas: 1
    workload:
      main:
        podSpec:
          containers:
            main:
              env: 
                API_PORT: "10018"
                LOG_LEVEL: debug
                DB_ENGINE: postgres
                POSTGRES_USER: mealie
                POSTGRES_SERVER: mealie-cnpg-main-rw
                POSTGRES_DB: mealie
                POSTGRES_PORT: "5432"
                POSTGRES_PASSWORD:
                  secretKeyRef:
                    name: mealie-cnpg-main-user
                    key: password
                    expandObjectName: false
              envFrom:
                - secretRef:
                    name: mealie-oidc
                    expandObjectName: false
   
