apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mealie
spec:
  values:
    mealie:
      api:
        general:
          baseUrl: https://mealie.staging.myrobertson.net
        oidc:
          client_id: "mealie_staging"
    server:
      controllers:
        main:
          replicas: 1
   