apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: probe-noenc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: csi-cephfs-sc-noenc-test
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: probe-enc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: csi-cephfs-sc
