apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: immich
spec:
  values:
    server:
      controllers:
        main:
          replicas: 3
          containers:
            main:
              image:
                tag: v2.6.3
              env:
                IMMICH_TELEMETRY_INCLUDE: all
    machine-learning:
      controllers:
        main:
          replicas: 3
          containers:
            main:
              image:
                tag: v2.6.3
    valkey:
      controllers:
        main:
          replicas: 1
   
