apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: immich
spec:
  values:
    controllers:
      main:
        replicas: 1
        containers:
          main:
            image:
              tag: v2.2.3
    server:
      controllers:
        main:
          replicas: 1
          strategy: Recreate
   
