apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: immich
  namespace: immich
spec:
  values:
    controllers:
      main:
        containers:
          main:
            image:
              tag: v1.142.0
    server:
      controllers:
        main:
          replicas: 0
   