apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
  - ../../base/immich
  - httpRoute.yaml
patches:
  - path: immich-cluster.yaml
    target:
      kind: Cluster
  - path: ../../base/immich/release-ceph-cutover.yaml
    target:
      kind: HelmRelease
      name: immich
  - path: immich-values.yaml
    target:
      kind: HelmRelease
  - patch: |
      - op: replace
        path: /spec/resources/requests/storage
        value: 300Gi
    target:
      kind: PersistentVolumeClaim
      name: immich-data-files-pvc