apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
  - ../../base/immich
  - httpRoute.yaml
  - postgres-scheduled-backup.yaml
patches:
  - path: ../../base/immich/release-ceph-cutover.yaml
    target:
      kind: HelmRelease
      name: immich
  - path: immich-values.yaml
    target:
      kind: HelmRelease
  - patch: |
      - op: replace
        path: /spec/resources/requests/storage
        value: 300Gi
    target:
      kind: PersistentVolumeClaim
      name: immich-data-files-pvc-ceph
  - patch: |
      - op: add
        path: /spec/backup
        value:
          barmanObjectStore:
            destinationPath: s3://homelab-prod-backups/cnpg/cluster-immich-ceph
            endpointURL: https://s3.us-west-2.amazonaws.com
            wal:
              compression: gzip
              encryption: AES256
            data:
              compression: gzip
              encryption: AES256
            s3Credentials:
              accessKeyId:
                name: cnpg-backup-s3
                key: AWS_ACCESS_KEY_ID
              secretAccessKey:
                name: cnpg-backup-s3
                key: AWS_SECRET_ACCESS_KEY
          retentionPolicy: 30d
    target:
      kind: Cluster
      name: cluster-immich-ceph