apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: nextcloud-search
  labels:
    app.kubernetes.io/name: nextcloud-search
    app.kubernetes.io/component: search
    app.kubernetes.io/part-of: nextcloud
spec:
  version: 8.17.4
  http:
    tls:
      selfSignedCertificate:
        disabled: true
  nodeSets:
    - name: default
      count: 1
      config:
        node.store.allow_mmap: false
        xpack.security.enabled: false
      podTemplate:
        spec:
          containers:
            - name: elasticsearch
              resources:
                requests:
                  cpu: 250m
                  memory: 2Gi
                limits:
                  cpu: "2"
                  memory: 2Gi
      volumeClaimTemplates:
        - metadata:
            name: elasticsearch-data
          spec:
            accessModes:
              - ReadWriteOnce
            storageClassName: ceph-block
            resources:
              requests:
                storage: 10Gi
