apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: trilium-pve3-migration
  namespace: default
spec:
  type: kv-v2
  mount: secret
  path: trilium/prod/migration
  refreshAfter: 60s
  destination:
    create: true
    name: trilium-pve3-migration
