apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vikunja-data
  labels:
    app.kubernetes.io/name: vikunja
    app.kubernetes.io/component: app
    app.kubernetes.io/part-of: task-control-plane
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: csi-cephfs-sc
