apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: task-control-plane-vikunja
  labels:
    app.kubernetes.io/part-of: task-control-plane
spec:
  type: kv-v2
  mount: secret
  path: task-control-plane/env/vikunja
  refreshAfter: 60s
  destination:
    create: true
    name: task-control-plane-vikunja
