apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: whisparr
spec:
  values:

    whisparr:
      api:
        general:
          baseUrl: https://whisparr.staging.myrobertson.net
    workload:
      main:
        replicas: 0
   