apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: plex
spec:
  values:
    pms:
      resources:
        requests:
          cpu: 500m
          memory: 1Gi
        limits:
          cpu: 4000m
          memory: 8Gi
    extraVolumes:
      - name: media4k
        nfs:
          server: scooter.myrobertson.net
          path: /volume1/plex
      - name: radarr-media
        nfs:
          server: scooter.myrobertson.net
          path: /volume1/radarr/radarr
    extraVolumeMounts:
      - name: media4k
        mountPath: /plex
      - name: radarr-media
        mountPath: /radarr
