apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: plex
spec:
  values:
    plex:
      disableGDM: false
      requireHTTPS: false

    resources:
      limits:
        cpu: 4000m
        memory: 8Gi
        gpu.intel.com/i915: "1"

    workload:
      main:
        podSpec:
          containers:
            main:
              securityContext:
                privileged: false
                allowPrivilegeEscalation: false
              env:
                ALLOWED_NETWORKS: "172.16.0.0/12,10.0.0.0/8,192.168.0.0/16"
