apiVersion: v1
kind: Secret
metadata:
  name: authelia-ldap-ca
type: Opaque
stringData:
  myrobertson-dc1-ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIDkTCCAnmgAwIBAgIQbF/+UropyJJDIybKYxHWGjANBgkqhkiG9w0BAQsFADBP
    MRMwEQYKCZImiZPyLGQBGRYDbmV0MRswGQYKCZImiZPyLGQBGRYLbXlyb2JlcnRz
    b24xGzAZBgNVBAMTEm15cm9iZXJ0c29uLURDMS1DQTAeFw0yNTEwMDgxNjA4NDNa
    Fw0zMDEwMDgxNjE4NDJaME8xEzARBgoJkiaJk/IsZAEZFgNuZXQxGzAZBgoJkiaJ
    k/IsZAEZFgtteXJvYmVydHNvbjEbMBkGA1UEAxMSbXlyb2JlcnRzb24tREMxLUNB
    MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAuywOllpF0hUOy/wtCPZL
    s8AMujvYEzaKoDoVYHyTH4KozAVAnuQwoBFvSs5Vzhh3RXyde4vV8kYP3dRLU3H8
    o3MB6g0CkB/229r6QBjkeHUdqC9iViRID6Ayyiw8Y0/WtI4HoF+NYEsSVxcIdg3d
    Smq1iC/vNhCnnrhydlmHya4B823/5SEvVAAzHmFi5KlebtQinN3tbEpnf3T2KdSq
    zHk8JJtCiloWMVI/2MLYr6PvBnA72DooeZ5ZV2x5185R/Vsd4q5D8HUPXjDnVG+7
    BUEh9A9bblJqmAN6CdC0JyY6G4+jVv0Ex8NfA/9OsAqJA/QPfxEiQ7NFIMONAVeI
    NQIDAQABo2kwZzATBgkrBgEEAYI3FAIEBh4EAEMAQTAOBgNVHQ8BAf8EBAMCAYYw
    DwYDVR0TAQH/BAUwAwEB/zAdBgNVHQ4EFgQUsZJHlspjMaonYzRUZ3pH9q51guMw
    EAYJKwYBBAGCNxUBBAMCAQAwDQYJKoZIhvcNAQELBQADggEBAB0OQSSsBgtYcfLJ
    l1HS2a2Wplrvms09Cyqc0dKZDDjPdC4VM0UyektRui5/qo5nERASfs3nz491ex1u
    ZFzpw3Kf/aUgnaQIZzKKQrU4alEFGTJhJQv4QSE5wiO1asHlFa/Z8Nw4ViHm1Rlg
    lTtlJRY0XW2vbSOpJCiOAU/ZS6MIF3kqJlTitgsWNT8rO+p6Oy6PX22jwh1Foa8i
    x03+h2L3BR4ZDHMTIauMsoyyWhE0FSK6icvMyQoasZ+Oi0NHhLL7JYsgECxl8af+
    EXtMCwioMHky8ZQXMcfHdSKMoH6HiyW4aAkv6z7VgRzRH85xUpo0VbHo+pQ1K190
    S30eyiw=
    -----END CERTIFICATE-----
  myrobertson-dc1-ca-1.crt: |
    -----BEGIN CERTIFICATE-----
    MIICCDCCAa+gAwIBAgIQF9zxtm7FcrlB+hsJIdZ7mzAKBggqhkjOPQQDAjBRMRMw
    EQYKCZImiZPyLGQBGRYDbmV0MRswGQYKCZImiZPyLGQBGRYLbXlyb2JlcnRzb24x
    HTAbBgNVBAMTFG15cm9iZXJ0c29uLURDMS1DQS0xMB4XDTI1MTAyMDE3MjMxNFoX
    DTQwMTAyMDE3MzMwN1owUTETMBEGCgmSJomT8ixkARkWA25ldDEbMBkGCgmSJomT
    8ixkARkWC215cm9iZXJ0c29uMR0wGwYDVQQDExRteXJvYmVydHNvbi1EQzEtQ0Et
    MTBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABK+4DJe8IQJfxAzy0rPHXzB90y6j
    VH8DIkZ7MVKDiU3I4wvijS377qYF29isRM7PAIJqoBn2qrj3tq0VXf2kVqejaTBn
    MBMGCSsGAQQBgjcUAgQGHgQAQwBBMA4GA1UdDwEB/wQEAwIBhjAPBgNVHRMBAf8E
    BTADAQH/MB0GA1UdDgQWBBRDeCmhtlyh4RyCRpNsWwmHhSQIiTAQBgkrBgEEAYI3
    FQEEAwIBADAKBggqhkjOPQQDAgNHADBEAiBanuCZDMRVikhd3L9npjlcU/RfYTM9
    KBEosp9OrdExBwIgMyq4owAejBTFfxDEco8n/Si9OBQLLZ01n+vwnwLr964=
    -----END CERTIFICATE-----