---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cluster-authelia-ceph
  namespace: default
spec:
  instances: 1
  enableSuperuserAccess: false
  storage:
    size: 10Gi
    storageClass: synology-iscsi-storage
  managed:
    roles:
      - name: authelia
        superuser: false
        login: true
  bootstrap:
    initdb:
      database: authelia
      owner: authelia