apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: authelia
spec:
  values:
    persistence:
      enabled: true
      existingClaim: authelia-config-ceph
    pod:
      env:
        - name: AUTHELIA_STORAGE_POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: cluster-authelia-ceph-app
              key: password
    configMap:
      storage:
        postgres:
          address: tcp://cluster-authelia-ceph-rw.default.svc.cluster.local:5432