apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: authelia
spec:
  releaseName: authelia
  postRenderers:
    - kustomize:
        patches:
          - target:
              kind: Deployment
              name: authelia
            patch: |
              apiVersion: apps/v1
              kind: Deployment
              metadata:
                name: authelia
              spec:
                template:
                  spec:
                    volumes:
                      - name: secrets
                        secret:
                          items:
                            - key: identity_validation.reset_password.jwt.hmac.key
                              path: identity_validation.reset_password.jwt.hmac.key
                            - key: session.encryption.key
                              path: session.encryption.key
                            - key: authentication.ldap.password.txt
                              path: authentication.ldap.password.txt
                            - key: storage.encryption.key
                              path: storage.encryption.key
                            - key: storage.postgres.password.txt
                              path: storage.postgres.password.txt
                            - key: identity_providers.oidc.hmac.key
                              path: identity_providers.oidc.hmac.key
  chart:
    spec:
      chart: authelia
      version: "0.10.49"
      sourceRef:
        kind: HelmRepository
        name: authelia
  interval: 50m
  install:
    remediation:
      retries: 10
  values:
    pod:
      kind: Deployment
      replicas: 1
    secret:
      existingSecret: authelia-secret
    configMap:
      authentication_backend:
        ldap:
          enabled: true
          implementation: 'activedirectory'
          address: 'ldap://rhonda.myrobertson.net'
          base_dn: 'cn=Users,dc=myrobertson,dc=net'
          user: 'ldap@myrobertson.net'

      session:
        name: 'authelia_session'
        same_site: 'lax'
        inactivity: '5m'
        expiration: '1h'
        remember_me: '1M'
        cookies:
          - domain: "myrobertson.com"
            authelia_url: "https://auth.myrobertson.com"
          - domain: "myrobertson.net"
            authelia_url: "https://auth.staging.myrobertson.net"

      access_control:
        default_policy: 'deny'
        rules:
          - domain: '*.myrobertson.com'
            policy: 'one_factor'
          - domain: '*.myrobertson.net'
            policy: 'one_factor'

      storage:
        postgres:
          enabled: true
          username: 'authelia'
          address: 'tcp://cluster-authelia-rw.default.svc.cluster.local:5432'
      
      notifier:
        filesystem:
          enabled: true

      log:
        level: debug
