apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: authelia
spec:
  releaseName: authelia
  postRenderers:
    - kustomize:
        patches:
          - target:
              kind: Deployment
              name: authelia
            patch: |
              apiVersion: apps/v1
              kind: Deployment
              metadata:
                name: authelia
              spec:
                template:
                  spec:
                    volumes:
                      - name: secrets
                        secret:
                          items:
                            - key: identity_validation.reset_password.jwt.hmac.key
                              path: identity_validation.reset_password.jwt.hmac.key
                            - key: session.encryption.key
                              path: session.encryption.key
                            - key: authentication.ldap.password.txt
                              path: authentication.ldap.password.txt
                            - key: storage.encryption.key
                              path: storage.encryption.key
                            - key: storage.postgres.password.txt
                              path: storage.postgres.password.txt
                            - key: identity_providers.oidc.hmac.key
                              path: identity_providers.oidc.hmac.key
                            - key: identity_providers.oidc.jwks.key
                              path: identity_providers.oidc.jwks.key
                      - name: db-secret
                        secret:
                          secretName: cluster-authelia-ceph-app
                          optional: true
                          items:
                            - key: password
                              path: storage.postgres.password.txt
          - target:
              kind: Deployment
              name: authelia
            patch: |
              apiVersion: apps/v1
              kind: Deployment
              metadata:
                name: authelia
              spec:
                template:
                  spec:
                    containers:
                      - name: authelia
                        env:
                          - name: AUTHELIA_SERVER_DISABLE_HEALTHCHECK
                            value: "true"
                          - name: AUTHELIA_IDENTITY_VALIDATION_RESET_PASSWORD_JWT_SECRET_FILE
                            value: /secrets/internal/identity_validation.reset_password.jwt.hmac.key
                          - name: AUTHELIA_SESSION_SECRET_FILE
                            value: /secrets/internal/session.encryption.key
                          - name: AUTHELIA_AUTHENTICATION_BACKEND_LDAP_PASSWORD_FILE
                            value: /secrets/internal/authentication.ldap.password.txt
                          - name: AUTHELIA_STORAGE_ENCRYPTION_KEY_FILE
                            value: /secrets/internal/storage.encryption.key
                          - name: AUTHELIA_STORAGE_POSTGRES_PASSWORD_FILE
                            value: /secrets/db/storage.postgres.password.txt
                          - name: X_AUTHELIA_CONFIG
                            value: /configuration.yaml
                          - name: X_AUTHELIA_CONFIG_FILTERS
                            value: template
                        volumeMounts:
                          - name: db-secret
                            mountPath: /secrets/db
                            readOnly: true
  chart:
    spec:
      chart: authelia
      version: "0.10.49"
      sourceRef:
        kind: HelmRepository
        name: authelia
  interval: 50m
  install:
    remediation:
      retries: 10
  values:
    pod:
      kind: Deployment
      replicas: 1
    secret:
      existingSecret: authelia-secret
    configMap:
      authentication_backend:
        ldap:
          enabled: true
          implementation: 'activedirectory'
          address: 'ldaps://rhonda.myrobertson.net'
          tls:
            server_name: 'rhonda.myrobertson.net'
            skip_verify: false
            certificate_chain: |
              -----BEGIN CERTIFICATE-----
              MIIDkTCCAnmgAwIBAgIQbF/+UropyJJDIybKYxHWGjANBgkqhkiG9w0BAQsFADBP
              MRMwEQYKCZImiZPyLGQBGRYDbmV0MRswGQYKCZImiZPyLGQBGRYLbXlyb2JlcnRz
              b24xGzAZBgNVBAMTEm15cm9iZXJ0c29uLURDMS1DQTAeFw0yNTEwMDgxNjA4NDNa
              Fw0zMDEwMDgxNjE4NDJaME8xEzARBgoJkiaJk/IsZAEZFgNuZXQxGzAZBgoJkiaJ
              k/IsZAEZFgtteXJvYmVydHNvbjEbMBkGA1UEAxMSbXlyb2JlcnRzb24tREMxLUNB
              MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAuywOllpF0hUOy/wtCPZL
              s8AMujvYEzaKoDoVYHyTH4KozAVAnuQwoBFvSs5Vzhh3RXyde4vV8kYP3dRLU3H8
              o3MB6g0CkB/229r6QBjkeHUdqC9iViRID6Ayyiw8Y0/WtI4HoF+NYEsSVxcIdg3d
              Smq1iC/vNhCnnrhydlmHya4B823/5SEvVAAzHmFi5KlebtQinN3tbEpnf3T2KdSq
              zHk8JJtCiloWMVI/2MLYr6PvBnA72DooeZ5ZV2x5185R/Vsd4q5D8HUPXjDnVG+7
              BUEh9A9bblJqmAN6CdC0JyY6G4+jVv0Ex8NfA/9OsAqJA/QPfxEiQ7NFIMONAVeI
              NQIDAQABo2kwZzATBgkrBgEEAYI3FAIEBh4EAEMAQTAOBgNVHQ8BAf8EBAMCAYYw
              DwYDVR0TAQH/BAUwAwEB/zAdBgNVHQ4EFgQUsZJHlspjMaonYzRUZ3pH9q51guMw
              EAYJKwYBBAGCNxUBBAMCAQAwDQYJKoZIhvcNAQELBQADggEBAB0OQSSsBgtYcfLJ
              l1HS2a2Wplrvms09Cyqc0dKZDDjPdC4VM0UyektRui5/qo5nERASfs3nz491ex1u
              ZFzpw3Kf/aUgnaQIZzKKQrU4alEFGTJhJQv4QSE5wiO1asHlFa/Z8Nw4ViHm1Rlg
              lTtlJRY0XW2vbSOpJCiOAU/ZS6MIF3kqJlTitgsWNT8rO+p6Oy6PX22jwh1Foa8i
              x03+h2L3BR4ZDHMTIauMsoyyWhE0FSK6icvMyQoasZ+Oi0NHhLL7JYsgECxl8af+
              EXtMCwioMHky8ZQXMcfHdSKMoH6HiyW4aAkv6z7VgRzRH85xUpo0VbHo+pQ1K190
              S30eyiw=
              -----END CERTIFICATE-----
              -----BEGIN CERTIFICATE-----
              MIICCDCCAa+gAwIBAgIQF9zxtm7FcrlB+hsJIdZ7mzAKBggqhkjOPQQDAjBRMRMw
              EQYKCZImiZPyLGQBGRYDbmV0MRswGQYKCZImiZPyLGQBGRYLbXlyb2JlcnRzb24x
              HTAbBgNVBAMTFG15cm9iZXJ0c29uLURDMS1DQS0xMB4XDTI1MTAyMDE3MjMxNFoX
              DTQwMTAyMDE3MzMwN1owUTETMBEGCgmSJomT8ixkARkWA25ldDEbMBkGCgmSJomT
              8ixkARkWC215cm9iZXJ0c29uMR0wGwYDVQQDExRteXJvYmVydHNvbi1EQzEtQ0Et
              MTBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABK+4DJe8IQJfxAzy0rPHXzB90y6j
              VH8DIkZ7MVKDiU3I4wvijS377qYF29isRM7PAIJqoBn2qrj3tq0VXf2kVqejaTBn
              MBMGCSsGAQQBgjcUAgQGHgQAQwBBMA4GA1UdDwEB/wQEAwIBhjAPBgNVHRMBAf8E
              BTADAQH/MB0GA1UdDgQWBBRDeCmhtlyh4RyCRpNsWwmHhSQIiTAQBgkrBgEEAYI3
              FQEEAwIBADAKBggqhkjOPQQDAgNHADBEAiBanuCZDMRVikhd3L9npjlcU/RfYTM9
              KBEosp9OrdExBwIgMyq4owAejBTFfxDEco8n/Si9OBQLLZ01n+vwnwLr964=
              -----END CERTIFICATE-----
          base_dn: 'cn=Users,dc=myrobertson,dc=net'
          user: 'ldap@myrobertson.net'

      session:
        name: 'authelia_session'
        same_site: 'lax'
        inactivity: '5m'
        expiration: '1h'
        remember_me: '1M'
        cookies:
          - domain: "myrobertson.com"
            authelia_url: "https://auth.myrobertson.com"
          - domain: "myrobertson.net"
            authelia_url: "https://auth.staging.myrobertson.net"

      access_control:
        default_policy: 'deny'
        rules:
          - domain: '*.myrobertson.com'
            policy: 'one_factor'
          - domain: '*.myrobertson.net'
            policy: 'one_factor'

      storage:
        postgres:
          enabled: true
          username: 'authelia'
          address: 'tcp://cluster-authelia-rw.default.svc.cluster.local:5432'
      
      notifier:
        filesystem:
          enabled: true

      log:
        level: debug
