apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: authelia
spec:
  releaseName: authelia
  postRenderers:
    - kustomize:
        patches:
          - target:
              kind: Deployment
              name: authelia
            patch: |
              apiVersion: apps/v1
              kind: Deployment
              metadata:
                name: authelia
              spec:
                template:
                  spec:
                    volumes:
                      - name: secrets
                        secret:
                          optional: true
                          items:
                            - key: identity_validation.reset_password.jwt.hmac.key
                              path: identity_validation.reset_password.jwt.hmac.key
                            - key: session.encryption.key
                              path: session.encryption.key
                            - key: authentication.ldap.password.txt
                              path: authentication.ldap.password.txt
                            - key: storage.encryption.key
                              path: storage.encryption.key
                            - key: storage.postgres.password.txt
                              path: storage.postgres.password.txt
                            - key: identity_providers.oidc.hmac.key
                              path: identity_providers.oidc.hmac.key
                            - key: identity_providers.oidc.jwks.key
                              path: identity_providers.oidc.jwks.key
                            - key: pve_oidc
                              path: pve_oidc
                            - key: pbs_oidc
                              path: pbs_oidc
                            - key: synology_scooter_oidc
                              path: synology_scooter_oidc
                            - key: synology_kermit_oidc
                              path: synology_kermit_oidc
                      - name: db-secret
                        secret:
                          secretName: cluster-authelia-ceph-app
                          optional: true
                          items:
                            - key: password
                              path: storage.postgres.password.txt
                      - name: ldap-ca-certs
                        secret:
                          secretName: authelia-ldap-ca
          - target:
              kind: Deployment
              name: authelia
            patch: |
              apiVersion: apps/v1
              kind: Deployment
              metadata:
                name: authelia
              spec:
                template:
                  spec:
                    containers:
                      - name: authelia
                        env:
                          - name: AUTHELIA_SERVER_DISABLE_HEALTHCHECK
                            value: "true"
                          - name: AUTHELIA_IDENTITY_VALIDATION_RESET_PASSWORD_JWT_SECRET_FILE
                            value: /secrets/internal/identity_validation.reset_password.jwt.hmac.key
                          - name: AUTHELIA_SESSION_SECRET_FILE
                            value: /secrets/internal/session.encryption.key
                          - name: AUTHELIA_AUTHENTICATION_BACKEND_LDAP_PASSWORD_FILE
                            value: /secrets/internal/authentication.ldap.password.txt
                          - name: AUTHELIA_STORAGE_ENCRYPTION_KEY_FILE
                            value: /secrets/internal/storage.encryption.key
                          - name: AUTHELIA_STORAGE_POSTGRES_PASSWORD_FILE
                            value: /secrets/db/storage.postgres.password.txt
                          - name: AUTHELIA_CERTIFICATES_DIRECTORY
                            value: /certificates
                          - name: X_AUTHELIA_CONFIG
                            value: /configuration.yaml
                          - name: X_AUTHELIA_CONFIG_FILTERS
                            value: template
                        volumeMounts:
                          - name: db-secret
                            mountPath: /secrets/db
                            readOnly: true
                          - name: ldap-ca-certs
                            mountPath: /certificates
                            readOnly: true
  chart:
    spec:
      chart: authelia
      version: "0.10.49"
      sourceRef:
        kind: HelmRepository
        name: authelia
  interval: 50m
  install:
    remediation:
      retries: 10
  values:
    pod:
      kind: Deployment
      replicas: 1
    secret:
      existingSecret: authelia-secret
    configMap:
      authentication_backend:
        ldap:
          enabled: true
          implementation: 'activedirectory'
          address: 'ldaps://rhonda.myrobertson.net'
          tls:
            server_name: 'rhonda.myrobertson.net'
            skip_verify: false
          base_dn: 'cn=Users,dc=myrobertson,dc=net'
          user: 'ldap@myrobertson.net'

      session:
        name: 'authelia_session'
        same_site: 'lax'
        inactivity: '5m'
        expiration: '1h'
        remember_me: '1M'
        cookies:
          - domain: "myrobertson.com"
            authelia_url: "https://auth.myrobertson.com"
          - domain: "myrobertson.net"
            authelia_url: "https://auth.staging.myrobertson.net"

      access_control:
        default_policy: 'deny'
        rules:
          - domain: '*.myrobertson.com'
            policy: 'one_factor'
          - domain: '*.myrobertson.net'
            policy: 'one_factor'

      storage:
        postgres:
          enabled: true
          username: 'authelia'
          address: 'tcp://cluster-authelia-ceph-rw.default.svc.cluster.local:5432'
      
      notifier:
        filesystem:
          enabled: true

      log:
        level: debug
