apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: authelia
spec:
  values:
    persistence:
      enabled: true
      existingClaim: authelia-config-ceph
    configMap:
      storage:
        postgres:
          address: tcp://cluster-authelia-ceph-rw.default.svc.cluster.local:5432