---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: authelia-secret
  namespace: default
spec:
  type: kv-v2
  mount: secret
  path: authelia/stage
  refreshAfter: 60s
  destination:
    create: true
    name: authelia-secret
