apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: whisparr
spec:
  values:

    whisparr:
      api:
        general:
          baseUrl: https://whisparr.myrobertson.com
    workload:
      main:
        replicas: 0
    persistence:
      media:
        enabled: true
      downloads:
        enabled: true
   