---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: syncthing
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: syncthing
  values:
    persistence:
      config:
        storageClass: synology-iscsi-storage
      immich-data-files-pvc:
        enabled: true
        existingClaim: immich-data-files-pvc
        mountPath: /var/immich-data
        readOnly: true