---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: syncthing
spec:
  suspend: true
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: syncthing
  values:
    workload:
      main:
        replicas: 0
        podSpec:
          containers:
            main:
              securityContext:
                runAsUser: 0
                runAsNonRoot: false
                privileged: true
    persistence:
      config:
        storageClass: csi-cephfs-sc
        existingClaim: syncthing-config-ceph
      
      downloads:
        enabled: false
        type: nfs
        mountPath: /var/downloads
        path: /volume1/downloads/
        server: scooter.myrobertson.net
        targetSelectAll: true

      immich-data-files-pvc:
        enabled: true
        existingClaim: immich-data-files-pvc-ceph
        mountPath: /var/immich-data
        readOnly: true
    service:
      listeners:
        enabled: true
        type: LoadBalancer
        ports:
          tcp:
            enabled: true
            port: 22000
            targetPort: 22000
      listeners-udp:
        enabled: true
        type: LoadBalancer
        ports:
          udp:
            enabled: true
            port: 22000
            targetPort: 22000
            protocol: udp
      discovery:
        enabled: true
        type: LoadBalancer
        ports:
          discovery:
            enabled: true
            port: 21027
            targetPort: 21027
            protocol: udp