apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: intel-device-plugins-operator
spec:
  interval: 30m
  chart:
    spec:
      chart: intel-device-plugins-operator
      sourceRef:
        kind: HelmRepository
        name: intel
      interval: 12h
  values:
    manager:
      devices:
        fpga: true
        gpu: true
