apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: readarr
spec:
  values:

    readarr:
      api:
        general:
          baseUrl: https://readarr.staging.myrobertson.net
    workload:
      main:
        replicas: 0
