name: Secret Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  gitleaks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@e07f1cb9b4e024213dfed9d5a8193ee9b4253ac3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
