---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: immich
  annotations:
    cert-manager.io/cluster-issuer: vault-issuer
    cert-manager.io/common-name: immich.dev.myrobertson.net
    cert-manager.io/private-key-algorithm: "ECDSA"
    cert-manager.io/dns-names: immich.myrobertson.com
spec:
  gatewayClassName: istio
  listeners:
  - name: immich
    hostname: immich.dev.myrobertson.net
    port: 443
    protocol: HTTPS
    allowedRoutes:
      namespaces:
        from: All
    tls:
      mode: Terminate
      certificateRefs:
      - name: immich-cert
  infrastructure:
    labels:
      istio-injection: enabled
    annotations:
      external-dns.alpha.kubernetes.io/hostname: immich.dev.myrobertson.net
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: immich
spec:
  # Match the generated Deployment by reference
  # Note: Do not use `kind: Gateway`.
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: immich-istio
  minReplicas: 2
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: immich
spec:
  minAvailable: 1
  selector:
    # Match the generated Deployment by label
    matchLabels:
      gateway.networking.k8s.io/gateway-name: immich
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: immich
spec:
  parentRefs:
  - name: immich
  hostnames: ["immich.dev.myrobertson.net"]
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: immich-server
      port: 2283