apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: immich
resources:
  - gateway.yaml
  - imageCatalog.yaml
  - namespace.yaml
  - postgres.yaml
  - pvc.yaml
  - repository.yaml
  - release.yaml
