---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cluster-immich-ceph 
spec:
  instances: 1
  enableSuperuserAccess: true
  storage:
    size: 10Gi
    storageClass: ceph-block
  imageName: ghcr.io/tensorchord/cloudnative-pgvecto.rs:16.5-v0.3.0@sha256:be3f025d79aa1b747817f478e07e71be43236e14d00d8a9eb3914146245035ba
  postgresql:
    shared_preload_libraries:
      - "vectors.so"
  managed:
    roles:
      - name: immich
        superuser: true
        login: true
  bootstrap:
    initdb:
      database: immich
      owner: immich
      postInitApplicationSQL:
        - CREATE EXTENSION IF NOT EXISTS "vectors";
        - CREATE EXTENSION IF NOT EXISTS "cube" CASCADE;
        - CREATE EXTENSION IF NOT EXISTS "earthdistance" CASCADE;
        - ALTER ROLE immich SET search_path TO '"$user"', public, vectors;
