
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cluster-immich
spec:
  instances: 1
  storage:
    size: 10Gi
    storageClass: synology-iscsi-storage
    pvcTemplate:
      accessModes:
        - ReadWriteMany
  # enableSuperuserAccess: false
  imageName: ghcr.io/tensorchord/cloudnative-vectorchord:16.9-0.4.3

  # postgresUID: 26

  postgresql:
    shared_preload_libraries:
      - "vchord.so"
  managed:
    roles:
      - name: immich
        superuser: false
        login: true
  bootstrap:
    initdb:
      database: immich
      owner: immich
      secret:
        name: immich-postgres-user
      # TODO: Use managed extensions (pg 18)
      postInitApplicationSQL:
        # Commands based on: https://immich.app/docs/administration/postgres-standalone/#without-superuser-permission
        - CREATE EXTENSION vchord CASCADE;
        - CREATE EXTENSION earthdistance CASCADE;

---
apiVersion: v1
stringData:
  DB_USERNAME: immich
  DB_DATABASE_NAME: immich
  DB_PASSWORD: immich
  username: immich
  password: immich
kind: Secret
metadata:
  name: immich-postgres-user
type: kubernetes.io/basic-auth

---
apiVersion: batch/v1
kind: Job
metadata:
  name: change-pvc-permissions
spec:
  template:
    spec:
      initContainers:
        - name: volume-permissions
          image: busybox # Or any image with 'chown', 'chmod' utilities
          imagePullPolicy: IfNotPresent
          env:
            - name: VOLUME_MOUNT_PATH
              value: /var/lib/postgresql/data # Adjust to your PVC's mount path
            - name: TARGET_USER_ID
              value: "26" # Target user ID
            - name: TARGET_GROUP_ID
              value: "26" # Target group ID
          command:
            - sh
            - -c
            - |
              chown -R $TARGET_USER_ID:$TARGET_GROUP_ID $VOLUME_MOUNT_PATH
              chmod -R 775 $VOLUME_MOUNT_PATH # Adjust permissions as needed
              echo 'Volume permissions updated'
          volumeMounts:
          - name: pgdata
            mountPath: /var/lib/postgresql/data
      containers:
        - name: dummy-container # A placeholder container, as the main work is in initContainer
          image: busybox
          command: ["sh", "-c", "echo 'Permissions changed, job complete'; sleep 30"]
      volumes:
      - name: pgdata
        persistentVolumeClaim:
          claimName: cluster-immich-1
      restartPolicy: OnFailure
