
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cluster-immich
  namespace: immich
spec:
  instances: 3
  storage:
    size: 4Gi
    storageClass: ceph-filesystem
    pvcTemplate:
      accessModes:
        - ReadWriteMany
  imageName: ghcr.io/tensorchord/cloudnative-vectorchord:16.9-0.4.3

  postgresql:
    enableSuperuserAccess: true
    shared_preload_libraries:
      - "vchord.so"
  managed:
    roles:
      - name: immich
        superuser: true
        login: true
  bootstrap:
    initdb:
      database: immich
      owner: immich
      secret:
        name: immich-postgres-user
      # TODO: Use managed extensions (pg 18)
      postInitApplicationSQL:
        # Commands based on: https://immich.app/docs/administration/postgres-standalone/#without-superuser-permission
        - CREATE EXTENSION vchord CASCADE;
        - CREATE EXTENSION earthdistance CASCADE;

---
apiVersion: v1
stringData:
  DB_USERNAME: immich
  DB_DATABASE_NAME: immich
  DB_PASSWORD: immich
  username: immich
  password: immich
kind: Secret
metadata:
  name: immich-postgres-user
  namespace: immich
type: kubernetes.io/basic-auth