---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-data-files-pvc-v2
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 320Gi
  storageClassName: synology-iscsi-storage
  volumeMode: Filesystem
