apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-data-pvc
  namespace: immich
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 300Gi
  storageClassName: csi-cephfs-sc
  volumeMode: Filesystem
