---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: immich
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: immich
  values:
    server:
      controllers:
        main:
          containers:
            main:
              env:
                DB_USERNAME:
                  valueFrom:
                    secretKeyRef:
                      name: cluster-immich-app
                      key: username
                DB_PASSWORD:
                  valueFrom:
                    secretKeyRef:
                      name: cluster-immich-app
                      key: password
                DB_DATABASE_NAME:
                  valueFrom:
                    secretKeyRef:
                      name: cluster-immich-app
                      key: dbname
                DB_HOSTNAME: "cluster-immich-rw"
    
          replicas: 0
          affinity:
            podAntiAffinity:
              preferredDuringSchedulingIgnoredDuringExecution:
                - weight: 100
                  podAffinityTerm:
                    labelSelector:
                      matchLabels:
                        app.kubernetes.io/name: server
                    topologyKey: "kubernetes.io/hostname"

    immich:
      metrics:
        # Enabling this will create the service monitors needed to monitor immich with the prometheus operator
        enabled: true
      persistence:
        # Main data store for all photos shared between different components.
        library:
          # Automatically creating the library volume is not supported by this chart
          # You have to specify an existing PVC to use
          existingClaim: immich-data-files-pvc

    valkey:
      enabled: true
      persistence:
        data:
          accessMode: ReadWriteMany
          size: 10Gi
          storageClass: synology-iscsi-storage
