apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-config-ceph
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
  storageClassName: csi-cephfs-sc
