apiVersion: v1
kind: Service
metadata:
  name: plex-lan
  namespace: default
  labels:
    app.kubernetes.io/name: plex
spec:
  type: LoadBalancer
  loadBalancerIP: 10.31.0.67
  selector:
    app.kubernetes.io/instance: plex
    app.kubernetes.io/name: plex-media-server
  ports:
    - name: pms
      port: 32400
      targetPort: 32400
      protocol: TCP
